### ISSUE TITLE
Documentation: Sphinx

### ISSUE THREAD

**Issue by jdsika** [habanoz/tezos-reward-distributor#100]
In general it is state of the art to use [Sphinx](http://www.sphinx-doc.org/en/master/) for the auto generation of a documentation using e.g. TravisCI. The BakingBad project around PyTezos is also [using it](https://baking-bad.github.io/pytezos/). I propose to retain the minimum instructions in the readme and shift the extended documentation to an online Sphinx website.

**Comment by habanoz** [comment]
This would be really nice to have.
