### ISSUE TITLE
Are payouts merged, when owner and founder address is the same? 

### ISSUE THREAD

**Issue by amani1104** [habanoz/tezos-reward-distributor#101]
I don't think it is a bug, rather a misunderstanding on my side on how calculations are made and how payouts for owner and founder are merged and sent to one address (when owner and founder are the same). As mentioned, I have set the same address in the founders map and the owners map, like this: 

founders_map :{KT1xxx: 1}
owners_map : {KT1Txxx: 1}   

I see the following log output: 

> Reward created for address FOUNDERS_PARENT type FOUNDERS_PARENT balance       0.00 ratio xxxx fee_ratio 0.000000 amount    xxxx fee_amount 0.00 fee_rate 0.00 payable False skipped False atphase 0 desc

What does the "payable False skipped" mean in this context? I have the impression that the fees collected by the baker are not added to the founder's payout, as the amount calculated for the founder, ie the balance of the baker, seems to be correct. But likely I'm missing something. 

I'm running TRD version 5.13

**Comment by habanoz** [comment]
Payable false means this amount will not be paid. Skipped false means this amount is not skipped either. FOUNDERS_PARENT is a middle level calculation entity. 

Calculations are done in separate consecutive steps. You should have a look at them to understand what really happens. For each account a reward ratio is calculated, founders and owner payments ratios are calculated, payments going to the same addresses are merged, if requested redirected to other addresses. At final step ratios are converted to actual payment amounts. 

Payment amounts are calculated at the very last step to minimize floating point errors.

**Comment by amani1104** [comment]
Thank you for this explanation. While writing this issue I discovered an error in how I specified the founder and owner address: I was leaving out a space after the colon for the founders map. This apparently resulted in the issue that founder rewards are calculated, but not payed out. After fixing this, founder and owner are merged correctly. Reminds me on the importance to double and triple check everything, as small errors sometimes can have huge impact. 

In addition, the address for owner and founder are also delegated to the baker. I see in the output that the reward is calculated correctly from the balance of this address. However, I do not get a separate payout to this address. Or is this also merged with payout and owner?

**Comment by habanoz** [comment]
There is a reward calculation report file. You can see more details in that file. For calculations look at ~/pymnt/reports/tzXXXXX/calculations directory.

A particular address only gets one payment, all rewards are merged according to the destination address.

**Comment by habanoz** [comment]
Closing. If you have more questions, you may re-open.
