### ISSUE TITLE
Founders/Supporters/Owners confusion

### ISSUE THREAD

**Issue by utdrmac** [habanoz/tezos-reward-distributor#102]
I'm not sure where/how to configure this, so figured best to ask here. Essentially, I've got a delegate who should not receive rewards. Their share should still be calculated as if they were being sent rewards, but TRD should not actually send them. Their share of rewards should just remain in baker's tz1.

What is the correct way to configure this?

**Comment by amani1104** [comment]
```
rules_map: {
KT1...: TOB
}
```
TOB: To baker
TOE: To everyone 
TOF: To founder

**Comment by utdrmac** [comment]
Thanks!

**Comment by habanoz** [comment]
@utdrmac 
Delegates are not meant to be excluded from receiving rewards. It is possible to leave all delegate shares by leaving owner and/or founder list empty. But it is not possible to provide a incomplete list of founders or owners.

Regards

**Comment by utdrmac** [comment]
@habanoz This "supporter" is neither founder nor owner. They are a regular KT1 delegate. But, due to special arrangement I have with them, they should not receive their share of rewards but their share should still be considered/calculated for all other KT1 delegates.

**Comment by utdrmac** [comment]
This falls under similar situation where a baker has stated "any delegates after cycle XX will not be paid rewards". There should be a way to configure these delegates to not receive anything and instead their share just remain in the tz1 baker's balance.

**Comment by habanoz** [comment]
If we are talking about delegators (KT addresses can only be delegators), not delegates, then amani1104's answer is accurate. A tiny correction here:

TOB actually means "to balance", which means to leave at the staking balance.

**Comment by amani1104** [comment]
Thanks. Corrected it in my comment. I struggled for some time to understand these abbreviations and meanings, as the old way to exclude delegators was deprecated without me noticing. Probably the new, improved way to exclude delegators should be more visibly described. I only found it by scrolling through discussion.

**Comment by habanoz** [comment]
Sorry, documentation is not perfect. Because TRD is not a funded project.  It is me and other few community members who try to keep it running in our spare time.
