### ISSUE TITLE
tzscan close 

### ISSUE THREAD

**Issue by goodpen** [habanoz/tezos-reward-distributor#104]
tzscan shutdown in this week. need new api

**Comment by SemElVik** [comment]
+.
which explorer will we use now?  
let's see what the response from habanoz

**Comment by goodpen** [comment]
maybe this tezos.id only this explorer show correct data

**Comment by SemElVik** [comment]
total we have: 
`tezos.id` 
`tzstats.com` 

+ beta ver.
`https://mvp.tezblock.io` 
`https://arronax-beta.cryptonomic.tech/#/`

**Comment by jdsika** [comment]
@amzid will Test the implementation using a local archive node. Start synchronizing now

**Comment by MrZeke** [comment]
im running archive nodes.  Will i be able to still pay out 5 cycles in advance ?

**Comment by utdrmac** [comment]
What about those of us not using archive mode?
Is there an option to use an external RPC endpoint instead of local node?

**Comment by gizmokrang** [comment]
Maybe we can use this https://tzstats.com/docs/api/index.html#introduction

**Comment by dawsy8888** [comment]
Hi ! what is the syntax to use -P rpc  ?  Also does the scrip use tezos-client for local rpc, and if so can I set the client config to use a remote rpc ?

**Comment by gizmokrang** [comment]
https://gitlab.com/tezos-southeast-asia/tezos.id-doc/blob/dev/Api.md

**Comment by habanoz** [comment]
We are waiting for @amzid to test on a local archive node. In order to activate rpc mode use with -P rpc option.

Not everybody may have an archive mode, for that case, there is public rpc mode which can be activated using -P prpc. The problem with prpc is we do not have a reliable public RPC service. If you know one, please share.

After switching to rpc/prpc mode it is not possible to pay in advance. Rpc implementation looks at the unfrozen rewards.

**Comment by dawsy8888** [comment]
Does https://tzstats.com/docs/api/index.html#introduction help ?

**Comment by tulpenhaendler** [comment]
Just wanted to say i run a public rpc endpoint here: 

https://rpc.tulip.tools/mainnet/chains/main/blocks/head

if that helps

For those of you running a archive node (@jdsika ) , there are snaphsots to speed up the process:

https://twitter.com/Blindripper85/status/1184155202762489857

without that syncing can take quite a while, make sure you have fast disks, ssd or nvme!

**Comment by habanoz** [comment]
> https://rpc.tulip.tools/mainnet/chains/main/blocks/head

Thanks for this information. This can be useful. I will try to change prpc mode to use this endpoint.

**Comment by habanoz** [comment]
https://rpc.tulip.tools/mainnet/chains/main/blocks/614401/context/raw/json/rolls/owner/snapshot/150/

returning 502. This endpoint is not usable.

**Comment by habanoz** [comment]
Reverted back to tezrpc. It is not very responsive but works. New default provider is "prpc". Doing a git pull is enough. 

Tezrpc it does not provide zeronet (babylon) endpoint. Unable to test for zeronet.

**Comment by jdsika** [comment]
@habanoz be aware that Babylon is on a branch called "babylonnet"

**Comment by habanoz** [comment]
@jdsika I was not aware, I was thinking it is being tested on zeronet.

**Comment by goodpen** [comment]
i have this error
Error:
  Rpc request failed:
     - meth: POST
     - uri: http://localhost:8732/chains/main/blocks/head/helpers/scripts/run_operation
     - error: Oups! It looks like we forged an invalid HTTP request.
                Failed to parse the request body: Missing object field branch

**Comment by amani1104** [comment]
You could also use our public node: https://teznode.letzbake.com

 I just upgraded it to archive. It should be quite fast and responsive, as it is not under heavy load.

**Comment by habanoz** [comment]
@goodpen can you please create another issue?

Please run with -V mode and share the log file.

**Comment by amani1104** [comment]
Thanks for the notice. It works now.

**Comment by FreedomPrevails** [comment]
@amani1104 You are right, this endpoint uses a ridiculous amount of resources. It returns the chosen snapshot for a particular cycle. tezos devs need to fix the node performance, it doesnt make sense.

**Comment by utdrmac** [comment]
That's the wrong dang RPC to use to determine which snapshot was chosen for a roll.

Use this one, much, much faster:
https://teznode.letzbake.com//chains/main/blocks/614401/context/raw/json/cycle/150

**Comment by amani1104** [comment]
Great, that is really much faster! Please use this one stated by @utdrmac. I worried that the node would become unusable at the beginning of each cycle, when everyone calls this endpoint to pay out their delegators  :-)

**Comment by utdrmac** [comment]
@amani1104 do you have a web cache in place? all this info is static. after first person hits it, it should be cached by squidproxy or nginx plugin (or whatever web server you're using).

**Comment by amani1104** [comment]
Not yet, I will work on that. It was not needed before, as almost no one except myself and another guy were using the node.

**Comment by utdrmac** [comment]
@amani1104 Using the example above, snapshot 7, that means level 587776 is the snapshot block.
```
$ curl https://teznode.letzbake.com/chains/main/blocks/587776/
Sorry, this RPC is not supported by LetzBake!
```

**Comment by amani1104** [comment]
> Are you running this node on a SSD server ?

@FreedomPrevails Yes, SSD with 50'000 IOPS.

**Comment by utdrmac** [comment]
You only need like 3 or 4 RPC endpoints to calculate rewards. The roll snapshot, above, the staking balance of the baker at said snapshot, below, and the balance of each delegate at the same snapshot.

Taken from github.com/DefinitelyNotAGoat/go-tezos (of which, I'm a contributor :) )

```
Staking balance of baker at block:
query := "/chains/main/blocks/" + snapShotLevel + "/context/delegates/" + bakerAddress + "/staking_balance"

Balance of each delegate at block:
query := "/chains/main/blocks/" + snapshotLevel + "/context/contracts/" + delegateAddress + "/balance"
```

**Comment by amani1104** [comment]
> $ curl https://teznode.letzbake.com/chains/main/blocks/587776/
> Sorry, this RPC is not supported by LetzBake!

Thanks, the endpoint works now.

**Comment by utdrmac** [comment]
@amani1104 Sure?
```
$ date
Thu Oct 17 19:31:22 UTC 2019
$ curl https://teznode.letzbake.com/chains/main/blocks/587776/
Sorry, this RPC is not supported by LetzBake!
```

**Comment by amani1104** [comment]
Yes, without the slash at the end: 

curl https://teznode.letzbake.com/chains/main/blocks/587776

It has to do with the way I constructed the whitelist.

**Comment by amani1104** [comment]
If you find more endpoints that do not work, please let me know. I launched the node a few months back, but since the announcement of TzScan to close shop there was almost no interest from the community, so I did not get much feedback.

**Comment by utdrmac** [comment]
@amani1104 Going to need the ones I mentioned above:
```
$ curl https://teznode.letzbake.com/chains/main/blocks/587776/context/delegates/tz1RV1MBbZMR68tacosb7Mwj6LkbPSUS1er1/staking_balance
Sorry, this RPC is not supported by LetzBake!

$ curl https://teznode.letzbake.com/chains/main/blocks/587776/context/contracts/KT1Xstn162HLVJqYbPB7PBizqm2DTcRw6Eqn/balance
"1491696227"
```

**Comment by amani1104** [comment]
Ok, the first one also works now with all tz1 addresses or everything after .../delegates/

**Comment by habanoz** [comment]
@amani1104 
Currently tezrpc is being used. Your public node can be used in near future, even better we can leave the selection to the user.

@utdrmac recommended endpoints can be used. Thanks for suggestions.

**Comment by jdsika** [comment]
@amzid You can set this issue resolved through the tzstats PR you are preparing.

**Comment by utdrmac** [comment]
This can be closed now right?
