### ISSUE TITLE
Pay frozen rewards

### ISSUE THREAD

**Issue by EdouardLvdl** [habanoz/tezos-reward-distributor#111]
**Describe the bug**
2019-10-18 09:44:55,408 - producer  - Checking for pending payments : checking 159 <= 160 - (5 + 1) - -5
2019-10-18 09:44:55,408 - producer  - Payment cycle is 159
2019-10-18 09:45:39,224 - producer  - Please wait until the rewards and fees for cycle 159 are unfrozen
2019-10-18 09:45:39,225 - producer  - Total rewards before processing is 0 mutez.
2019-10-18 09:45:39,225 - producer  - Total payment amount is 0. Nothing to pay!

**To Reproduce**
python3 src/main.py -D -R -5 -M 3 -C 159

**Expected behavior**
Should calculate and pay rewards even if frozen

**Environment**
Latest origin/master

**Additional context**
Babylon upgrade happened, we upgraded to the latest available version of TRD this morning
Is this due to Tzscan API deactivated? We usually pay frozen rewards. How to do if not running an archive node? Thanks for your help

**Comment by habanoz** [comment]
Current RPC based reward logic looks at the amount of unfrozen rewards. I do not know a method to calculate unfrozen rewards. 

If you have a method, please share.

Regards

**Comment by beofor** [comment]
The method to calculate frozen rewards is the same as unfrozen reward calc, but it should be done for all blocks of __cycle-5__ and for __change__ records with positive sign..

**Comment by EdouardLvdl** [comment]
Looks like Tez-baker is able to calculate frozen rewards https://docs.google.com/spreadsheets/d/1scqNd9tM5iEkd2M-_pCTx5OGy1hNvvouDSXqDjdQn2s/edit#gid=0 using API 
https://mystique.tzkt.io/v3/

I have not yet dug into the formula

**Comment by jdsika** [comment]
@amzid this should definitly only be enabled though an additional flag e.g. `--pay-frozen-rewards` to make sure it is not happening by accident!

**Comment by habanoz** [comment]
@jdsika 

In order to pay for frozen rewards user need to specify negative values to -R parameter, which cannot easily happen by mistake? 

Additional option to prevent such a mistake, IMHO, only helps increasing complexity.

**Comment by EdouardLvdl** [comment]
The -R parameter has worked well so far for us
To avoid mistakes, the dry-run option has been perfect

**Comment by jdsika** [comment]
I talked to  @amzid and he said that the -R command can only be used with tzstats because we cannot querry the frozen rewards easily with RPC. Paying frozen rewards will be enabled in combination with the tzstats feature. -R with pRPS or RPC will result in a message saying it is not possible.

**Comment by jdsika** [comment]
@EdouardLvdl can you please try again with the newest version and apply with range [-1,-5] and dryrun? Look at  #128 and comment there - I am closing this one.
