### ISSUE TITLE
Logging of operation hash / cleanup fee.ini / documentation of values

### ISSUE THREAD

**Issue by jdsika** [habanoz/tezos-reward-distributor#115]
**Is your feature request related to a problem? Please describe.**
Through the Babylon 2.0.1 upgrade the gas limits and fees for transactions have changed. This is related to #112 and #113 .

[Reference](https://blog.nomadic-labs.com/babylon-update-instructions-for-delegation-wallet-developers.html)

> Gas cost recap:
> Due to the changes brought by Babylon, gas costs will change and will probably change again in the future. Ideally, the gas cost of a transaction should be queried from a trusted node or indexer. For convenience, we list recommended gas costs for the most important cases below.
> 
> implicit (tz) to implicit: 10307
> implicit to manager.tz: 15385
> manager.tz to implicit: 26283
> manager.tz to manager.tz: 44725

**Describe the solution you'd like**
We disabled the KT address payout which makes 15385 the upper boundary making. Both values should be integrated into the configuration in order to switch values according to the different transfer types which should be detected automatically:

> implicit (tz) to implicit: 10307
> implicit to manager.tz: 15385

Last reported working values are the following:
```
[DEFAULT]
fee=1792

[KTTX]
storage_limit=0
gas_limit=15385
base=100
```
The `base` values should be removed as it is not used in the code and is misleading.

Logging instructions from #113 must be included in the documentation. Change debug level for operation hash.

Write justification for chosen values into the fee.ini file through a comment.

**Comment by amzid** [comment]
The last PR #144 implements the requested documentation and improves the descriptions in the help section.
