### ISSUE TITLE
Rewards for Cycle Significantly Short

### ISSUE THREAD

**Issue by sriney-staked** [habanoz/tezos-reward-distributor#117]
**Describe the bug**
For Cycle 155, I am on a synched full node (Babylon) and using a remote archive node to generate payouts.

`python3 src/main.py --verbose -D -C 155 -M 3 -P prpc -A 136.243.240.44:443`

The amount of rewards that TRD reports for my baker is two orders of magnitude smaller than tzstats reports.

I can provide my baker address if someone can't reproduce it with another baker.

**Comment by habanoz** [comment]
Very little information is provided.

Please provide your baking configuration file and log file. Also what you get with tzstats?

You can choose not to reveal baking address.

**Comment by jdsika** [comment]
@sriney-staked this should be fixed. Can you please try with the newest master version?
