### ISSUE TITLE
destination_map does not redirect payments

### ISSUE THREAD

**Issue by dansan566** [habanoz/tezos-reward-distributor#120]
**Describe the bug**
I specified a payout redirect in the .yaml configuration file under rules_map. Unfortunately, the reward was not redirected and was not displayed in the calculation CSV. It is possible that destination_map does not work? 

**To Reproduce**
Our rules_map looks as follows:
rules_map:
  KT-Contract-1: TOF
  KT-Contract-2: TOF
  TZ-Address-1: TOF
  TZ-Address-2: TOF
  **KT-Contract-3: TZ-Address-3**
  mindelegation: TOB

_KT-Contract-3 and TZ-Address are also defined under supporters_set_

**Expected behavior**
I did expect that the Payouts will be redirected from KT-Contract-3 to TZ-Address-3. 

**Screenshots**
When running:
```
  ],
  "__destination_map": {
   "KT-Contract-3": "TZ-Address-3"
  }
```

**Environment**
 - Source Code Build (c4c5c9f886c02785d1dc886c1e9ebd59d4dd3448)
 - Archive-Node on Mainnet-Staging
 - python3 src/main.py -C 156 -D -P rpc -M 3 --verbose

Edit: I also checked the case where KT-Contract-3 and TZ-Address are not included in the supporters_set. Same issue.

**Comment by jdsika** [comment]
@amzid this is still an issue as reported today.
