### ISSUE TITLE
tzscan issues with configue

### ISSUE THREAD

**Issue by chiptus** [habanoz/tezos-reward-distributor#121]
**Describe the bug**
Trying to configure TRD, I get `Unable to find a live tzscan mirror. Consider using RPC api` when writing my baking address. I tried to understand how to use an RPC API but didn't find anything in the docs, so I started digging into the code. I found here: src/configure.py#L72 that it uses tzscan without any option to replace.

**To Reproduce**
1. run configure utility
2. write your baking address

**Expected behavior**
I expect it to work or at least tell me how to use an RPC api

**Comment by chiptus** [comment]
change the Provider to "rpc" fixed it for me, I'll try to make a PR to change from constant value to argument with default to "rpc"

**Comment by jdsika** [comment]
Could you retest with the newest merge removing all tzscan dependencies and replacing it by tzstats?

**Comment by chiptus** [comment]
there are still deps on tzscan in configure.py
