### ISSUE TITLE
failed preapplying found out that signature was wrong

### ISSUE THREAD

**Issue by chiptus** [habanoz/tezos-reward-distributor#123]
I'm not sure what causes this to happen on my computer. Maybe it's because I was running from mac. when running the normal process of `python ./src/main.sh -M 3` I received 

```
Error:
  Rpc request failed:
     - meth: POST
     - uri: http://192.168.1.19:8732/chains/main/blocks/head/helpers/preapply/operations
     - error: Oups! It looks like we forged an invalid HTTP request.
                Failed to parse the request body: Unhandled error (Failure "Unexpected data (Signature)")
```
After running in verbose mode I saw in app.log the request, and I seen that the signature is `Enter password for encrypted key: ${HASH}`  I wondered about that and went into simple_client_manager.py and changed `line.replace("Signature:","").strip()` to `line.replace("Enter password for encrypted key: Signature:","").strip()`

It solved my issue, but not sure if it won't be a problem to others

**Comment by jdsika** [comment]
@dansan566 could you quickly check this report on your mac, please?

**Comment by jdsika** [comment]
@chiptus can you please try it with the newest master? Daniel is running it with Tezos Signer and local node and tzstats and it works for him on MAC.

**Comment by chiptus** [comment]
I'll pull the new version and try soon

**Comment by jdsika** [comment]
I am closing this as well, feel free to reopen when you still have problems and provide as much debug information as possible.
