### ISSUE TITLE
How to change the standard data provider?

### ISSUE THREAD

**Issue by amani1104** [habanoz/tezos-reward-distributor#124]
Currently the standard data provider in TRD is https://mainnet.tezrpc.me. How can I change this to perform https-requests from another public archive node, like https://teznode.letzbake.com? 

I understand from [PR #122](https://github.com/habanoz/tezos-reward-distributor/pull/122) that this should be performed using e.g. -P rpc -A x.x.x.x:8732. However, doing this results in the following error: 

```
Error:
  Did not find service: GET http://127.0.0.1:8732/describe/teznode.letzbake.com:443/chains/main/blocks/head/context/constants?recurse=no
```

**Comment by utdrmac** [comment]
@amani1104 Use `-P prpc` .   "rpc" means use a node and RPC commands. "prpc" means to use a public/http RPC

**Comment by amani1104** [comment]
I tried the following command:
```
python3 src/main.py -V -E /usr/local/bin -C 158 -M 3 -P prpc -A https://teznode.letzbake.com:443 -D 
```

Unfortunately, I get the same error: 
```
Did not find service: GET http://127.0.0.1:8732/describe/teznode.letzbake.com:443/chains/main/blocks/head/context/constants?recurse=no
```

Obviously TRD still requests data from the local node.

**Comment by amzid** [comment]
The current implementation caused apparently some conflicts when being used in other parts in code. That is why I changed the way it is implemented by adding a new parameter `-Ap` which is only responsible for the public node url. Theoretically, now you can run your node using `-Ap https://teznode.letzbake.com`, however you will notice that letzbake do not allow all calls that are needed for the TRD. You can indeed get the head block info and some other basic info, but not the snapshot block where we can get the relevant list of delegators. I am not sure whether this node is an archive node or not.
For example, try opening this url in the browser and you will get an error message which you do not get when requesting the head block. The same url works fine when you use tezrpc. I hope this solves your issue.

**Comment by amani1104** [comment]
Yes, with this solution it is now possible to query another node. Many thanks for adding this option. 
I have added the respective endpoint to the whitelist of the node at https://teznode.letzbake.com, so that it can be used by TRD.
