### ISSUE TITLE
where is the line of code to change the API address ?

### ISSUE THREAD

**Issue by MrZeke** [habanoz/tezos-reward-distributor#125]
Im trying to find the part of the code that specifies the API address for this tool to run.  I would like to change the default API address away from tzscan to another address that has the same API as tzscan.

thanks in advance

**Comment by jdsika** [comment]
The newest master should work with tzstats. Did you try it?

**Comment by MrZeke** [comment]
I have not tried it.  Ill try it now.  I need to find a way to pay cycles in advance.  can tzstats do this ?

**Comment by jdsika** [comment]
@amzid is that feature already tested?

It is not possible with RPC or pRPC but should work with tzstats. There is still an open issue in their GitHub.

**Comment by MrZeke** [comment]
yeah i have tried this on the new master branch but i get the error it needs to wait until the rewards need to be unfrozen :/    hopefully a fix will come out soon..

**Comment by utdrmac** [comment]
@MrZeke you need to specify a negative value for `-R` if you want to pay out in advance.

**Comment by MrZeke** [comment]
@utdrmac this does not work.  I was doing this an i get an error saying it needs to wait until the rewards are unfrozen.

**Comment by utdrmac** [comment]
@MrZeke When you run this, is it showing the correct cycle that you want to process?

**Comment by utdrmac** [comment]
Try doing 1 cycle back, `-4`. Looking at this line, https://github.com/habanoz/tezos-reward-distributor/blob/bb76917b09d7e80d3d5a37b14558bfeb047a8e3a/src/rpc/rpc_reward_api.py#L66, it's checking if the rewards for the current cycle to process have been distributed, which is different from unfrozen. So if you are trying to pay out -5, then those will not be distributed until block 4095 of the current cycle. -4 should have been distributed on block 4095 of the previous cycle, so those should be available to pay out.

**Comment by jdsika** [comment]
@MrZeke and @utdrmac we just merged again. The tzstats integration was not ready before. Sorry for the confusion!

**Comment by jdsika** [comment]
We are currently in cycle 165 and the following line

`python3 src/main.py -C 164 -D -P tzstats -M 3 -R -5`

does the payout for cycle 164. Can you confirm that it works?

**Comment by MrZeke** [comment]
thanks @jdsika this works !!
