### ISSUE TITLE
Can you use a ledger nano s with TRD?

### ISSUE THREAD

**Issue by songproducer** [habanoz/tezos-reward-distributor#135]

**Comment by habanoz** [comment]
In principle it should be.

https://medium.com/cryptium/how-to-delegate-tezzies-tezos-xtz-with-your-ledger-nano-s-with-initial-setup-screenshots-519c9ae6654f

According to this article:

tezos-client list known addresses 

lists ledger related addresses. TRD interacts with tezos-client. If tezos-client sends transactions to ledger device for signing, it should be possible.

However, for each batch a button click will be needed. 

All this information is theoretical. I have never used ledger before.

**Comment by jdsika** [comment]
closing, please feel free to reopen when you have further questions
