### ISSUE TITLE
Balance is lower than expected

### ISSUE THREAD

**Issue by denver-s** [habanoz/tezos-reward-distributor#139]
**Describe the bug**
Running a dry-run test, the report shows that a certain KT1, which I delegated to my baker, has a balance lower than the real value.

**To Reproduce**
1. Run `python3 src/main.py -D -N MAINNET -C 168`
2. Go to reports folder and open file 168.csv

**Expected behavior**
Balance should be 1,163.062799 tz, while it shows 1,162.493050.

**Screenshots**

**Environment**
Configuration:

```
{
 "network": "MAINNET",
 "reward_data_provider": "prpc",
 "reports_base": "~/pymnt/reports",
 "config_dir": "~/pymnt/cfg",
 "node_addr": "127.0.0.1:8732",
 "node_addr_public": "https://mainnet.tezrpc.me",
 "dry_run": true,
 "dry_run_no_consumers": false,
 "executable_dirs": "~/,~/tezos",
 "docker": false,
 "verbose": false,
 "background_service": false,
 "do_not_publish_stats": false,
 "run_mode": 1,
 "release_override": 0,
 "payment_offset": 0,
 "initial_cycle": 168
}
```

**Comment by jdsika** [comment]
All good?

**Comment by denver-s** [comment]
Sorry, I did not check the balance 7 cycles before the cycle I was calculating.

**Comment by jdsika** [comment]
Your first solved issue :)
