### ISSUE TITLE
Changing minimum/trivial payout formula

### ISSUE THREAD

**Issue by utdrmac** [habanoz/tezos-reward-distributor#141]
We are getting lots of small delegations which translate to small reward payouts. I've noticed this log line that says "X non-trivial payments, total XXX.XXX". This made me dig into the code where I see that a payment is only considered payable if it is greater than 2e3 (2000) mutez (or 0.002 XTZ). This will certainly raise some comments about people not being rewarded.

Shouldn't the formula be: `if (reward - txnFee > 0.0){send_reward();}` ?
Obviously, if the baker is absorbing the txnFee themselves, then this translates to:
  `if (reward > 0.0){send();}`

**Comment by utdrmac** [comment]
What happens if I change `ZERO_THRESHOLD` to txnFee+0.00001 ? That way, script compares if reward > that value, and if we subtract fee, we still check/verify that there is 'something' to pay?

**Comment by amzid** [comment]
This is a good idea. In this way, we can avoid zero payments which are causing troubles for batch payments when applied for tz accounts and resolve issue #145 as well.
