### ISSUE TITLE
Issues with Batch Payments

### ISSUE THREAD

**Issue by dansan566** [habanoz/tezos-reward-distributor#145]
Describe the bug
Here is a collection of bugs concerning batch payments that I collected together with another Tezos Baker (Bake'n'Rolls).

To Reproduce

1. Issue: Patch payments cannot be executed if an address has been removed from the state tree. Quick-Fix: Exclude address and execute separately (incl. payment of burn fee) 
2. _Issue This time, 1 batch failed because of "Transaction Error proto.005-PsBabyM1.contract..empty_transaction" for this guy: https://tzstats.com/tz1cKfV8LNBGQ6DSnzR63j8Rq5g43AXbEJsD
The payout amount was 0.000000 XTZ and his balance was 4XTZ at the moment of payment.
Since 0.000000 XTZ payments are passing to the KT1 addresses, it seems that the issue is in the payout of 0 XTZ to the tz1 address.
Probably the resolution here is to avoid 0.000000 XTZ payments at all because they are no sense :)_

**Comment by jdsika** [comment]
@dansan566 can you please verify the fix and close the issue if you are ok with the solution?

**Comment by jdsika** [comment]
I think it is solved according to the conversations
