### ISSUE TITLE
Trivial/Not-Trival are backwards

### ISSUE THREAD

**Issue by utdrmac** [habanoz/tezos-reward-distributor#147]
**Describe the bug**
The word "trivial" is defined as "of very little importance or value; insignificant:"
Source: https://www.dictionary.com/browse/trivial?s=t
In the code, there are references to "non-trivial" and "trivial" payments. In the code, these are backwards; trivial references payments which will be made (which is not correct), and non-trivial payments which will not be made because they are too small.

This backwards definitions causes confusion while reading the code.

I will submit a PR to fix this later today.

**To Reproduce**
See code in src/pay/batch_payer.py

**Expected behavior**
N/A

**Environment**
All environments

**Comment by utdrmac** [comment]
@jdsika FYI, I think it's better to just remove the notion of "trivial"/"non-trivial" altogether. What's the point/purpose/reason behind splitting up small vs large rewards? If they are greater than 0.000001, then they should be paid yes?

**Comment by jdsika** [comment]
The only reason for separation would be to have an upper limit for payments per cycle which would in theory require kyc or similar. E.g. setting the bar to the maximum of allowed cash one time transactions

**Comment by utdrmac** [comment]
That should be something configurable then, right? Currently, `ZERO_THRESHOLD` is a static value. Is this now the same thing as "minimal payout"?
