### ISSUE TITLE
email.ini doesn't send emails

### ISSUE THREAD

**Issue by Xa52c** [habanoz/tezos-reward-distributor#148]
I have configured email.ini with the following info, but no emails are sent when running a DRY RUN.

[DEFAULT]
user=myuser@gmail.com
pass=mypassword
smtp.host=smtp.gmail.com
smtp.port=587
sender=myuser@gmail.com
recipients=myrecipient@gmail.com
use_ssl=True

**Comment by utdrmac** [comment]
I would imagine that DRY RUN would not send any emails because it is a DRY RUN. Does it work when DRY_RUN = false?

**Comment by Xa52c** [comment]
getting this error:

Traceback (most recent call last):
  File "/home/xxxx/tezos-reward-distributor/src/pay/payment_consumer.py", line 128, in run
    self.mm.send_payment_mail(pymnt_cycle, report_file, nb_failed, nb_injected)
  File "/home/xxxx/tezos-reward-distributor/src/emails/email_manager.py", line 70, in send_payment_mail
    self.default["recipients"], [payments_file])
  File "/home/xxxx/tezos-reward-distributor/src/emails/email_worker.py", line 45, in send
    smtp.login(self.user, self.password)
  File "/usr/lib/python3.7/smtplib.py", line 697, in login
    "SMTP AUTH extension not supported by server.")
smtplib.SMTPNotSupportedError: SMTP AUTH extension not supported by server.

**Comment by utdrmac** [comment]
https://stackoverflow.com/questions/37224073/smtp-auth-extension-not-supported-by-server

Edit this file,  src/emails/email_worker.py
Go to line 45 and make it look like this:
```

        smtp.connect(self.host, self.port)
        smtp.ehlo()
        smtp.starttls()
        smtp.ehlo()
        smtp.login(self.user, self.password)
        smtp.sendmail(self.sender, recipient_string, msg.as_string())
        smtp.close()

**Comment by utdrmac** [comment]
If that works for you, I'll submit a PR

**Comment by Xa52c** [comment]
i'll test during the next payment. it doesn't send during dry run (it should for testing purposes).

**Comment by Xa52c** [comment]
this is working now. it sends emails to the spam folder on gmail.
