### ISSUE TITLE
Better documentation for arguments

### ISSUE THREAD

**Issue by denver-s** [habanoz/tezos-reward-distributor#152]
**Is your feature request related to a problem? Please describe.**
I can't find an explanation for arguments like "-M 3" or "-P prpc". I know what they means but they should be described better, in my opinion.

**Describe the solution you'd like**
A better wiki section.

**Comment by jdsika** [comment]
Can you see if PR #144 helped you - we tried to make it better. We are also preparing a sphinx documentation replacing the wiki

**Comment by denver-s** [comment]
Oh sorry @jdsika I didn't see that PR! I'll look into it.
