### ISSUE TITLE
Batch transaction and delegator pays for fees: how is it handled?

### ISSUE THREAD

**Issue by denver-s** [habanoz/tezos-reward-distributor#154]
If the setting is `delegator_pays_xfer_fee = True`, how is the batch transaction fee calculated?

Let's say we have 50 delegators and can send the payouts in one batch transaction (I don't know if this is possibile).
Is the fee divided by the number of delegators?

**Comment by utdrmac** [comment]
The transfer fee applies to each transfer within the batch. If you pay 50 delegators in 1 batch, you still pay the xfer fee 50 times in that 1 batch. If set to True, then the xfer fee is subtracted from the reward just before being added to the batch.

**Comment by utdrmac** [comment]
Have a look here:
https://api.tzstats.com/explorer/op/opacBwMS1MP4QvgAhsQW9FAjVsHH8rZwoZ5CD8tKi9ks1intXKv
You can see the fee applies to each transfer.

**Comment by utdrmac** [comment]
@denver-s Question answered? Can this be closed?
