### ISSUE TITLE
Failed to acquire the protocol version from the node

### ISSUE THREAD

**Issue by denver-s** [habanoz/tezos-reward-distributor#156]
I have a node running on my LAN and I mapped it as "tezos-node-lan".

My configuration is:
```
MainThread - Arguments Configuration = {
 "initial_cycle": 170,
 "run_mode": 1,
 "release_override": 0,
 "payment_offset": 0,
 "network": "MAINNET",
 "node_addr": "tezos-node-lan:8732",
 "reward_data_provider": "rpc",
 "node_addr_public": "https://mainnet.tezrpc.me",
 "reports_base": "/tezos-reward-distributor/pymnt/reports",
 "config_dir": "/tezos-reward-distributor/pymnt/cfg",
 "dry_run": true,
 "dry_run_no_consumers": false,
 "executable_dirs": "/usr/local/bin",
 "docker": false,
 "background_service": false,
 "do_not_publish_stats": false,
 "verbose": true
}
```

I get this error:
```
Failed to acquire the protocol version from the node
Rpc request failed:
- meth: GET
- uri: http://localhost:8732/chains/main/blocks/head/protocols
- error: Unable to connect to the node: "Connection refused"
 ```

It should be `http://tezos-node-lan:8732/chains/main/blocks/head/protocols`.

I can't find in NetworkConfiguration.py anything related to this RPC GET command.

**Comment by utdrmac** [comment]
Look at the `--help` for `-A NODE_ADDR`

**Comment by chiptus** [comment]
I had it because rpc wasn't open on my node. Check `.tezos-node/config.json`

**Comment by utdrmac** [comment]
@chiptus Can this be closed then?

**Comment by chiptus** [comment]
Depends on @denver-s

**Comment by asbjornenge** [comment]
@utdrmac if you look at the "Arguments Configuration" output, @denver-s is likely passing `-A tezos-node-lan:8732` - so it should not try `localhost:8732` or...?

I'm having the same issue, here are my params;

```
-A tezpi1:8732 -C 121 -M 3 -D -E /usr/local/bin/ -P prpc -Ap https://rpc.tulip.tools/mainnet/
```

Wher tezpi1 is the hostname of one of my tezos nodes that can sign tx and make payments.

Seeing:

```
2019-12-28 16:15:57,627 - MainThread - Command failed, error is |Warning:
  Failed to acquire the protocol version from the node
  Rpc request failed:
     - meth: GET
     - uri: http://localhost:8732/chains/main/blocks/head/protocols
     - error: Unable to connect to the node: "Connection refused"

Error:
  Rpc request failed:
     - meth: GET
     - uri: http://localhost:8732/describe/chains/main/blocks/head/context/constants?recurse=no
     - error: Unable to connect to the node: "Connection refused"
```

**Comment by denver-s** [comment]
Sorry for the delay, as @asbjornenge reported, the problem persists. "localhost" is used even if the node address is different.

**Comment by utdrmac** [comment]
If you search the entire codebase for 'localhost', you'll get 0 findings:
`$ grep -r --exclude-dir=logs localhost *`
So there's nothing hardcoded in the code to use localhost. Must be a parameter somewhere that is not being passed and the default of tezos-client is being used.

**Comment by utdrmac** [comment]
@habanoz @jdsika This is a bug in how TRD passes the node address to `tezos-client`. Actually, I think it's a bug in tezos-client. You can see this by executing something like this manually:

`/tezos-client rpc get http://foo:8732/chains/main/blocks/head`

You will still get output because tezos-client strips off `http://foo:8732` when calling RPC via this method. Essentially this is the same as `/tezos-client rpc get /chains/main/blocks/head`

The call within the code needs to be modified to be like this:
```
./tezos-client -A foo -P 8732 rpc get /chains/main/blocks/head
Warning:
  Failed to acquire the protocol version from the node
  Rpc request failed:
     - meth: GET
     - uri: http://foo:8732/chains/main/blocks/head/protocols
     - error: Unable to connect to the node: "resolution failed: name resolution failed"

Error:
  Rpc request failed:
     - meth: GET
     - uri: http://foo:8732/describe/chains/main/blocks/head?recurse=no
     - error: Unable to connect to the node: "resolution failed: name resolution failed"
```

Notice how the URI of the error output from the -client is showing the correct hostname.

**Comment by utdrmac** [comment]
Please see if this fixes your issue.  I only did some preliminary testing.

https://github.com/habanoz/tezos-reward-distributor/pull/168

**Comment by asbjornenge** [comment]
@utdrmac tested and works for me 😬👍

**Comment by denver-s** [comment]
@utdrmac do you have an estimated time when #168 will be merged?

**Comment by utdrmac** [comment]
@denver-s Nope. I'm not privileged to handle PRs. I've got some more changes for this issue that I'm going to test on next cycle and then I'll push those as well.
