### ISSUE TITLE
TRD pays, but there is an exceptions

### ISSUE THREAD

**Issue by SemElVik** [habanoz/tezos-reward-distributor#157]
**Describe the bug**
This has been going on for several cycles. (~ 4). 

`requests.exceptions
.ReadTimeout: HTTPSConnectionPool(host='mainnet.tezrpc.me', port=443): Read timed out. (read timeout=5)`

`logger.error("Fetching delegator info failed {}, will retry", delegator)
Message: 'Fetching delegator info failed {}, will retry'
Arguments: ('KT1S-----fiWkY',)`

**Expected behavior**
execution without exception

**Environment**
 - Chain mainnet   (git branches are always the freshest)
 - python3 src/main.py -C 175 -M 3
---
[175 err.txt](https://github.com/habanoz/tezos-reward-distributor/files/3978846/175.err.txt)

**Comment by utdrmac** [comment]
Have you manually checked that delegators address? Does it show on other block explorers?

**Comment by SemElVik** [comment]
TRD shows different addresses each time.
I watched them on the blockchain., they are active.
the minimum delegation we have is 10 XTZ. if the delegation is less then we do not pay remuneration.
has something changed in the .yaml file?

**Comment by utdrmac** [comment]
Well, the error indicates issues fetching data from mainnet.tezrpc.me. Looks like it is timing out after 5 seconds. If you enable verbose mode, do you see more in the logs/app.log file?

**Comment by SemElVik** [comment]
[err.txt](https://github.com/habanoz/tezos-reward-distributor/files/3980443/err.txt)

but TRD pays

**Comment by utdrmac** [comment]
Hmm. Seems to be missing some log lines.
`src/rpc/rpc_reward_api.py` line 109 says to log the URL it's trying to access but I don't see that line in your err.txt

**Comment by SemElVik** [comment]
Today it ended with new mistakes.
I did not begin to create a new issues, as this is a consequence of one of the other.
[err-5.txt](https://github.com/habanoz/tezos-reward-distributor/files/3998659/err-5.txt)

many had similar mistakes today.

**Comment by utdrmac** [comment]
mainnet.tezrpc.me is down
need to find an alternative public RPC server

**Comment by SemElVik** [comment]
It worked well for me: `python3 src/main.py -C 177 -P tzstats -M 3`
but probably we should return to the documentation `python3 src/main.py -C 177 -M 3`

about a different -P rpc server I heard you.         ok.
I will close this issue.
