### ISSUE TITLE
TRANSACTION BACKTRACKED

### ISSUE THREAD

**Issue by goodpen** [habanoz/tezos-reward-distributor#159]
python3 src/main.py   -V   -C176 -M3
https://better-call.dev/main/opFFgKiEGSbd7X1Dr5pmDQjNg42Tv7eBUkDzMQFyJCrH66ipBK9
Storage quota exceeded for the operation
A script or one of its callee wrote more bytes than the operation said it would

balance more then needed. TDR is up to date

**Comment by jdsika** [comment]
I am pretty sure the problem is the following known one:

One of the receiver has a 0 balance and a burn is needed for the transaction to reveal the address again in order for it to be part of the context again.
@amzid is working on a solution to scan for the current balance of the accounts and increase the burn cap for specific transactions.

Please provide feedback if the failing transaction belongs to a 0 balance address

**Comment by goodpen** [comment]
tz1TbPpNy4DnNK2seLsvmy9qPydYthpPtUcs yes this account have 0. how i can solve this? send 1 tezos manual to hes address?

**Comment by goodpen** [comment]
solved. send 1 xtz help

**Comment by utdrmac** [comment]
@goodpen Can you re-open this? This will be an ongoing issue that needs a proper fix. It has happened to us and at least one other recently.

**Comment by SemElVik** [comment]
my minimum is set to 10XTZ. who has less on the balance sheet I do not pay.
but it was with me.
look this: https://github.com/habanoz/tezos-reward-distributor/issues/112#issuecomment-569202429

**Comment by amzid** [comment]
The minimum delegated amount is related to the snapshot cycle, whereas the current balance is actually what matters if the operation is backtracked/failed because of an emptied account.
Please try to set the maximum storage in fee.ini to 1000 for example and see if the problem is solved

**Comment by utdrmac** [comment]
@amzid I don't think changing the storage fee will matter. You have to burn 0.257 xtz to re-activate the zero-ed account which is different from storage, IIRC.

**Comment by SemElVik** [comment]
@amzid, if it message is addressed to me, then:
my problem was solved by increasing by `storage_limit=300`
even if the snapshot was taken at a balance of 0, in fact I do not pay anyone less than 10.
so it was not supposed to influence.  I pay after the fact.

**Comment by utdrmac** [comment]
@SemElVik If you had to pay someone 11xtz, and their current balance was 0xtz, then it would not work, even with storage_limit=300 because a 0xtz address becomes deactivated. You'd have to burn to reactivate it.

**Comment by SemElVik** [comment]
in this payment it was not my case.

as I understand it, now the implementation is such, that you need to focus on the error and look for the address that you need to burn.

**Comment by utdrmac** [comment]
Should the baker be responsible for paying the burn fee? What if you have 10 addresses which are all 0? Should the baker pay out an additional 2.57xtz to re-activate all those addresses? Should TRD subtract the burn fee? (This would need to be added to the code)

**Comment by utdrmac** [comment]
Related #167

**Comment by songproducer** [comment]
> Should the baker be responsible for paying the burn fee? What if you have 10 addresses which are all 0? Should the baker pay out an additional 2.57xtz to re-activate all those addresses? Should TRD subtract the burn fee? (This would need to be added to the code)

I’d like to have the option to automatically exclude (TOB) addresses that have 0 balance.

**Comment by jdsika** [comment]
I am in favor of making this a config

**Comment by utdrmac** [comment]
Just an FYI, making this change will require some significant modifications to the code. TRD does not currently check the current balance of each delegates' address. This logic would need to be added somewhere in the phases of processing payments to filter out those with 0 balance.

**Comment by Phlogi** [comment]
Why is this issue closed, how was it resolved?

**Comment by utdrmac** [comment]
@Phlogi Issue was closed because TRD now properly detects if the receiver address has a 0 balance and acts according to the baker's configuration.
