### ISSUE TITLE
Total rewards before/after processing

### ISSUE THREAD

**Issue by gaia** [habanoz/tezos-reward-distributor#161]
I am not sure i understand the Total rewards before/after processing lines. Would you mind explaining these 2 amounts?

Thanks Habanoz!

**Comment by utdrmac** [comment]
before processing = raw rewards to be paid out without any filtering or checking for founders/supporters with no fees, etc
after processing = after applying all calculations, filters, etc

```
    -- Phase0 : Provider Phase
    -- Phase1 : Total Rewards Phase
    -- Phase2 : Ratios Phase
    -- Phase3 : Founders Phase
    -- Phase4 : Split Phase
```
before = phase0 (from API)
after = after phase 0,1,2,3,&4 calculations/filters
