### ISSUE TITLE
[Errno -5] No address associated with hostname

### ISSUE THREAD

**Issue by Xa52c** [habanoz/tezos-reward-distributor#163]
running TRD as a service, was working ok

did a git pull

now getting the following error, no files for payment are being generated

[Errno -5] No address associated with hostname

config file is same as before when was working

**Comment by utdrmac** [comment]
mainnet.tezrpc.me is offline, which is the public RPC that TRD uses. Try a different public URL. I just tested this one:

https://rpc.tulip.tools/mainnet/

Example: `$ python3 src/main.py -P prpc -Ap https://rpc.tulip.tools/mainnet/`

**Comment by utdrmac** [comment]
Also working:
`$ python3 src/main.py -P prpc -Ap https://api.tezos.org.ua/`

**Comment by utdrmac** [comment]
@jdsika Can we get a Wiki page with a list of known good public RPC endpoints?

**Comment by Xa52c** [comment]
thanks that worked. so we have to process manually (not using service) until tezrpc.me is online again?

**Comment by utdrmac** [comment]
> so we have to process manually

Not at all. Just re-launch TRD using a new RPC url and everything will work just like it did before. tezrpc may never come back online.

**Comment by labeoVlad** [comment]
Thank you @utdrmac 
I used `python3 src/main.py -P prpc -Ap https://api.tezos.org.ua/` and it worked just fine 
Great hint

**Comment by utdrmac** [comment]
@Xa52c Can this be closed now?

**Comment by Xa52c** [comment]
@utdrmac how to specify the RPC url when running as a service?

**Comment by utdrmac** [comment]
Edit the service script. `systemctl edit --full tezos-reward.service` and put the parameter in the command to execute.
