### ISSUE TITLE
didn't pay for slashed

### ISSUE THREAD

**Issue by SemElVik** [habanoz/tezos-reward-distributor#166]
we had `slashed` in cycle 179., for not disclosing `nonce`. (14.487573xtz)
the TRD took this into account and did not pay the delegates., TRD subtracted 14.48... xtz. and no rewards  to all in accordance with their share.
this has not happened before.
there is no such setting in the `.yaml` file.

how to solve this in the future ... ..

**Comment by amzid** [comment]
Are you on the last TRD version? If I understood your problem correctly, this should have been fixed in https://github.com/habanoz/tezos-reward-distributor/commit/772ced7a4b035af12e8d5f96ff5bac89038fa65b

**Comment by SemElVik** [comment]
I'm on the latest version.
```Latest commit:```  `cd80e2d`

**Comment by amzid** [comment]
This is how rewards are calculated right now in TRD, lost revelation rewards are taken into account, this is unfortunately not configurable.
![15e65658c2d9e793](https://user-images.githubusercontent.com/33556352/71716059-d1f56c80-2e13-11ea-9017-23e8e1020563.png)

**Comment by SemElVik** [comment]
but TRD did not pay my `slashed`.
the program was supposed to pay in full.

this will happen in the future. because the situation will happen again. I do not transfer the `nonce` file when I switch another node (I just forget to transfer it). therefore, I cannot open it when I work on another node. but I’m ready to pay for it and give delegates what they have earned. 

I would now have to manually watch each delegate and his share of these `14.487573 xtz`.
when it's 150+ delegates it's problematic.

**Comment by amzid** [comment]
Exactely, TRD does not pay slashed rewards, it substructs it from the total reward amount. The computation of rewards is now hardcoded and not configurable and follows the logic in my comment above: blue is positive amount, red is negative/substracted (e.g. slashed revelation rewards are substructed) and white (not selected) is not considered at all (e.g. accusation deposits).

The overhead for implementation/configuration is considerable, especially in case of RPC reward queries. In fact, using the rpc provider logic parses the unfrozen reward amount after 5 cycles and pays it out, what was slashed is not unfrozen and cannot be considered in this way.

A quick fix for you is to use tzstats with (-P tzstats) and substitute the line 53 of src/tzstats/tzstats_reward_provider_helper.py with the accounting logic that you desire. For example, you may want to remove the substraction of `float(resp[idx_income_lost_revelation_rewards])))` from the equation in line 53.

I hope this will be helpful.

**Comment by SemElVik** [comment]
I will close the question.
and in the future I’ll try to implement this if (or when) a similar situation arises. 
thx
