### ISSUE TITLE
too many delegators in batch causes payment to fail

### ISSUE THREAD

**Issue by Xa52c** [habanoz/tezos-reward-distributor#167]
tried to process a batch payment with 62 payments fails

edited the config.yaml and set min delegation amount to higher number, retry

payment succeeds for a batch payment with 54 payments.

**Comment by utdrmac** [comment]
I believe this is more related to the amount of bytes within the overall operation, not specifically the number of transactions.

**Comment by Xa52c** [comment]
Any suggestions how to handle this? My delegates don't like the workaround of truncating the list of payments, what else can I do?

**Comment by jdsika** [comment]
Set the storage limit to 1000 and try again. 100pro it is not the amount of people. More likely a 0xtz transaction or the issue with needing to reveal an account which had been emptied out

**Comment by SemElVik** [comment]
@Xa52c  this problem was on earlier versions of TRD. it has been fixed for a long time.
I pay 150+ delegates each cycle. 
the issue is not what you are describing.

**Comment by Xa52c** [comment]
@jdsika was right, it was an account which was emptied out leaving 0tz and needing a reveal.

would be great if TRD could handle this gracefully rather than failing the batch for all delegators. also, it moves the file to 'Done' even when this payment fails - an unrelated bug.

**Comment by jdsika** [comment]
@amzid this last feedback is important an should be included. check account balance at payment cycle. if == 0 -> make note in log as info. Use higher fee for burn and make info in CSV?

**Comment by Xa52c** [comment]
@jdsika (i can't see how to manually exclude a 0tz address, is there a config param?)

**Comment by jdsika** [comment]
This is not possible yet. I recommend to just pay the burn cap for the reveal until there is an option for it

**Comment by Xa52c** [comment]
@jdsika how do we do that? this command gives an error: tezos-client reveal key for tz1daaggpxm3FYsXtLmZkDR3Q1tfieyEhd9U

**Comment by utdrmac** [comment]
You can ignore the address by setting it 'TOB' (to balance) in your .yaml file:

```
rules_map: {KT19bi9mhnXBytz2GLMuEcDvTU8c8MHs8Gm6: TOB},
```

You don't reveal the key because it's not your address. You just need to send the address some minor amount, like 0.00001 XTZ and pay the additional burn fee of 0.257 XTZ to re-activate it.
