### ISSUE TITLE
State management / Running on docker

### ISSUE THREAD

**Issue by asbjornenge** [habanoz/tezos-reward-distributor#170]
Hi there! And thanks for a great project 😊🎉

I would like to run TRD itself in a Docker container. The documentation mentions TRD keeps track of past payments and will handle retrys etc. This makes TRD a stateful application. How & where does TRD store it's stateful data?

For Docker I need to mount volumes for any disk data to survive a service restart. Would it be sufficient to mount a volume for the `reports` folder? Are some data stored elsewhere?

Thanks!

**Comment by utdrmac** [comment]
Your .yaml config too would need to be mounted. You could do this:
`docker ... -v /path/on/disk:/opt/trd ...`
and then pass these options to TRD: `-f /opt/trd/cfg/ -r /opt/trd/reports/`

**Comment by asbjornenge** [comment]
@utdrmac thanks a bunch! 😊
