### ISSUE TITLE
Payout of 1.78 xtz made for 2 xtz reward + self payment from delegate to itself.

### ISSUE THREAD

**Issue by gsampathkumar** [habanoz/tezos-reward-distributor#174]
The round has a total earned of 2 xtz which was completely owed to the delegate (no delegators yet at this cycle)

2 issues:

- The tezos-rewards-distributor caused the delegate address sent the reward to itself. It used to happen before but atleast it was the full 2 xtz - 0.002 xtz (i'm assuming txn fee)

- This time the reward was an odd looking 1.78 xtz again sent from the delegate to itself. Not sure why 0.22 xtz got deducted from the reward.

My config file: 

{baking_address: <baking address>, delegator_pays_xfer_fee: true,
    min_delegation_amt: 0.0, payment_address: <payment address name>,
    rules_map: {mindelegation: TOB}, service_fee: 0.0, specials_map: {}, supporters_set: !!set {}}

Would greatly appreciate some help and please let me know if additional info is needed

**Comment by SemElVik** [comment]
`delegator_pays_xfer_fee: true` 
if you want to pay the commission yourself then set to `false`

**Comment by gsampathkumar** [comment]
Doesn't seem like the fee should be 0.22 xtz. Usually they would be much smaller.

**Comment by SemElVik** [comment]
look at your `fee.ini` file 

now it should look something like this:
```[DEFAULT]
fee=1792

[KTTX]
storage_limit=0
gas_limit=15385
base=100
```

**Comment by gsampathkumar** [comment]
Yep it is, and so with a 2 xtz payout, 1.982xtz would be sent out. In the case I'm describing it's 1.78 xtz which isn't explained by the fee.

**Comment by utdrmac** [comment]
If you have no delegators, then TRD should not have taken any action. The config setting of 'TOB' means "to balance" which means, "don't do anything" and the rewards will stay in the bakers tz1.

**Comment by utdrmac** [comment]
@gsampathkumar Are you still experiencing any issues? Can this be closed?

**Comment by gsampathkumar** [comment]
This is no longer an issue @utdrmac Can be closed. Thank you.
