### ISSUE TITLE
Frozen rewards distribution - Payment succeeds but appears that Transactions did not go through 

### ISSUE THREAD

**Issue by gsampathkumar** [habanoz/tezos-reward-distributor#175]
Hi, 
   I was trying out the -R -5 option and it finished successfully with no errors. A few payments were even sent out successfully. 

However I noticed this set of red transactions on the block explorer, which appears to mean they have failed as the accounts involved did not receive their rewards (please see attached screenshots)

Any idea why the operations would go through successfully on the command line and fail here. There is no indication of the reason of failure on any Block explorer I checked. Please advise.

Also what is my course of action in these scenarios? Figure out which cycle failed even though it said it succeeded, delete those files from the reports directory and re-run?

![Screenshot from 2020-01-07 11-35-13](https://user-images.githubusercontent.com/894515/71872429-6cbab780-3142-11ea-9783-569d89c3134e.png)

**Comment by utdrmac** [comment]
@gsampathkumar Check a different block explorer like tzstats.com It will display the reason for the failed transaction. There's a good chance one of the address you sent to in the batch has 0xtz which is an issue.

**Comment by jdsika** [comment]
duplicate #178
