### ISSUE TITLE
exclude delegators

### ISSUE THREAD

**Issue by goodpen** [habanoz/tezos-reward-distributor#177]
how can i exclude a delegate?

**Comment by zcryptox** [comment]
Assuming ‘exclude’ mean no service fees charged to the delegate, add their KT1 address to the ‘supporters_set'


supporters_set : {KT1XXXXX}



On Jan 10, 2020, at 9:30 AM, Bey0nd <notifications@github.com<mailto:notifications@github.com>> wrote:


how can i exclude a delegate?

**Comment by goodpen** [comment]
Exclude mean do not pay reward

**Comment by songproducer** [comment]
rules_map : {
“tzAddressToExclude“ : “TOB”
}

**Comment by goodpen** [comment]
address must be in “”?

**Comment by goodpen** [comment]
Traceback (most recent call last):
  File "src/main.py", line 205, in <module>
    main(args)
  File "src/main.py", line 94, in main
    parser.validate()
  File "/home/ubuntu/tezos-reward-distributor/src/config/yaml_baking_conf_parser.py", line 38, in validate
    self.validate_dest_map(conf_obj)
  File "/home/ubuntu/tezos-reward-distributor/src/config/yaml_baking_conf_parser.py", line 279, in validate_dest_map
    addr_validator.validate(key)
  File "/home/ubuntu/tezos-reward-distributor/src/util/address_validator.py", line 16, in validate
    "Incorrect input in {}, address({}) length must be {}".format(self.context, address, PKH_LENGHT))
Exception: Incorrect input in rules_map, address(tz1hYCht2XiymBH1UUbe8Ai42AvsXjRx8SKY:TOB) length must be 36

**Comment by goodpen** [comment]
baking_address : tz
payment_address : tz
service_fee : 1
founders_map : {}
owners_map : {}
prcnt_scale : None
pymnt_scale : None
specials_map : {}
supporters_set : {}
min_delegation_amt : 100
excluded_delegators_set : {tz1hYCht2XiymBH1UUbe8Ai42AvsXjRx8SKY:TOB}
delegator_pays_xfer_fee : False
rules_map: {"tz1hYCht2XiymBH1UUbe8Ai42AvsXjRx8SKY:TOB"}

**Comment by songproducer** [comment]
> rules_map: {"tz1hYCht2XiymBH1UUbe8Ai42AvsXjRx8SKY“ : “TOB"}

Don’t use:
> excluded_delegators_set : {tz1hYCht2XiymBH1UUbe8Ai42AvsXjRx8SKY:TOB}

Also make sure to double check there are spaces either sides of the : and also double check double quotes are not copied (formatting issues can happen) - just type them in a code editing program

**Comment by goodpen** [comment]
thanks
