### ISSUE TITLE
Empty accounts cause script to make failed payments.

### ISSUE THREAD

**Issue by songproducer** [habanoz/tezos-reward-distributor#178]
**Describe the bug**
Currently the payment fails if someone empties their account completely.

Proposed solution:
Check delegate address for 0 balance and exclude it from receiving rewards until it has a positive balance

**To Reproduce**
1. Accept delegations
2. One of the delegates empties account but is owed a reward
3. All transactions are backtracked

**Comment by utdrmac** [comment]
Yep. This is a serious issue now. Last 2 cycles I've had failed/backtracked payments because of this.

Side note: Why isn't this caught during preapply stage?

**Comment by jdsika** [comment]
I raised the standard value for storage_limit in the fee.ini to 257 and this should make it possible to pay the burn. @amzid what do you think about the following:
* check balance on address for payout cycle
* if 0 balance check if *pay_for_burn* or similar setting in the config is true
* if false exclude address from payout and mark in CSV note as reward for the baker
* if true check if *storage_limit* is high enough -> if not throw error

**Comment by utdrmac** [comment]
I've got a PR in the works. Hoping to submit today. New parameters:
'reactivate_zeroed' T/F - what to do on finding zero-balance payee
'delegate_pays_ra_fee' T/F - delegate pays reactivation (burn) fee

So much that needs changing all throughout the code base.... taking much longer than I had expected.
