### ISSUE TITLE
Total rewards before/after processing remain the same before process is interrupted

### ISSUE THREAD

**Issue by DaylightCulture** [habanoz/tezos-reward-distributor#185]
While running the latest version, I realized both the processed payments before and after did not take out for the fee. Just recently upgraded to the mainnet version 28309c81cc485467f22fb55e96e89302e1f2cd8a and used a new snapshot.

2020-01-20 10:03:35,312 - MainThread - Producer "producer" started
Traceback (most recent call last):
  File "src/main.py", line 207, in <module>
    main(args)
  File "src/main.py", line 157, in main
    reactivate_zeroed=cfg.get_reactivate_zeroed(),
  File "/home/user/tezos-reward-distributor/src/model/baking_conf.py", line 75, in get_reactivate_zeroed
    return self.get_attribute(REACTIVATE_ZEROED)
  File "/home/user/tezos-reward-distributor/src/model/baking_conf.py", line 45, in get_attribute
    raise Exception("Attribute {} not found in application configuration.".format(attr))
Exception: Attribute reactivate_zeroed not found in application configuration.
2020-01-20 09:20:53,060 - producer  - Reward creation is done for cycle 186, created X rewards.
2020-01-20 09:21:03,067 - producer  - Run mode ONETIME satisfied. Terminating ...
2020-01-20 09:21:03,068 - producer  - Producer returning ...
Exception ignored in: <module 'threading' from '/usr/lib/python3.6/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 1294, in _shutdown
    t.join()
  File "/usr/lib/python3.6/threading.py", line 1056, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.6/threading.py", line 1072, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt

**Comment by amzid** [comment]
* Concerning the first question, the total amount after processing does not take into account the fees, however the configured excluded delegators and some other configured aspects. The fees are to be seen under the log item "Total amount to pay out" given by the consumer.
* Concerning the second question, you need to add two more configuration items to your config file which concern the reactivation fees. Please consider the changes in the example config file in PR https://github.com/habanoz/tezos-reward-distributor/pull/181

**Comment by dansan566** [comment]
**reactivate_zeroed**
True/False - If True, an account to be paid found with a 0 balance will be reactivated, incurring the necessary burn fee and storage, and rewards will be sent. If False, any account with a 0 balance will be skipped payment. This will be noted in the CSV report.

**delegator_pays_ra_fee**
True/False - Functions just like delegator_pays_xfer_fee, except refers to the burn/reactivation fee. If True, the burn fee is subtracted from the reward payment (ie: delegate pays). If False, burn fee is paid for by baker. If reactivate_zeroed: True and delegator_pays_ra_fee: True but the reward is smaller than the burn fee, their rewards will be ignored and will simply remain at the bakers address.

**Comment by DaylightCulture** [comment]
In regards to this issue then, I only need to edit my configure.py to make sure I have these two options below now included?

If a destination address has 0 balance, should burn fee be paid to reactivate? 1 for Yes, 0 for No. Type enter for Yes >
0
Who is going to pay for 0XTZ-balance reactivation/burn fee: 0 for delegator, 1 for delegate. Type enter for delegator >
1

**Comment by dansan566** [comment]
I've never worked with configure.py but you can go to `~/pymnt/cfg/` open your .yaml file with an editor and add the lines reactivate_zeroed : True/False and delegator_pays_ra_fee : True/False.

**Comment by dansan566** [comment]
The lines are not included in your "old" cfg file. There are only there if you create a new one with ```
cp tezos-reward-distributor/examples/tz1boot1pK9h2BVGXdyvfQSv8kd1LQM6H889.yaml ~/pymnt/cfg/
nano ~/pymnt/cfg/tz1boot1pK9h2BVGXdyvfQSv8kd1LQM6H889.yaml
```

Here is an example:
  
```
version : 1.0
baking_address : tz1boot1pK9h2BVGXdyvfQSv8kd1LQM6H889
payment_address : tz1boot1pK9h2BVGXdyvfQSv8kd1LQM6H889
service_fee : 4.5
founders_map : {tz1boot1pK9h2BVGXdyvfQSv8kd1LQM6H889: 0.3, KT1KLQbYFtFZ5mAEnfEMZaWYuNtCsGuP5cLS: 0.7}
owners_map : {tz1boot1pK9h2BVGXdyvfQSv8kd1LQM6H889: 0.3, KT1KLQbYFtFZ5mAEnfEMZaWYuNtCsGuP5cLS: 0.7}
specials_map : {KT19g4JHTd3QYuYcpKFFiwViEzQ5n6ovYx1V: 7.5}
supporters_set : {KT1SenDhs9rL9fpZV3cLRXFovEBafmGqkki8}
min_delegation_amt : 1000
**reactivate_zeroed : False**
delegator_pays_xfer_fee : True
**delegator_pays_ra_fee : True**
rules_map:
  KT1MMhmTkUoHez4u58XMZL7NkpU9FWY4QLn3: KT1MMhmTkUoHez4u58XMZL7NkpU9FWY4QLn0
  KT1D33n8zp1bqBkViiQtLLPLEGRW9xcqihY3: KT1MMhmTkUoHez4u58XMZL7NkpU9FWY4QLn0
  KT1Ao8UXNJ9Dz71Wx3m8yzYNdnNQp2peqtM0: TOE
  KT1VyxJWhe9oz3v4qwTp2U6Rb17ocHGpJmW0: TOB
  KT19cJWfbDNXT4azVbgTBvtLMeqweuHH8W20: TOF
  mindelegation: TOB
```

**Comment by DaylightCulture** [comment]
Input the change and it worked smoothly
