### ISSUE TITLE
minimum delegation ammount

### ISSUE THREAD

**Issue by goodpen** [habanoz/tezos-reward-distributor#19]
do not pay reward if delegation amount less than delegation service set. example: if minimum delegation amount 1000 xtz. who delegate less don't get reward

**Comment by habanoz** [comment]
In roadmap.

**Comment by utdrmac** [comment]
@goodpen Check out #28 
Right now, any reward that would have been sent to skipped delegator is returned to baker and not added to the total reward pool. If you think it should be option B, let me know and I'll adjust. option A was easiest to implement. :D

**Comment by jdsika** [comment]
My opinion would be to leave option A, because someone is delegating against the terms of the Baker which should benefit the Baker as well. The "cost" of implementing measures against small delegations is on the Baker side?
Or else, why should it be split amongst the ones delegating?

**Comment by habanoz** [comment]
I believe there is not enough reason to split share among delegators. Because delegators already take what they deserve. 

In my view, rewards that come from delegators violating the min amount policy should go to the bakers.

**Comment by habanoz** [comment]
@utdrmac thanks for implementing option A. 

I am closing this issue. Anyone can re-open it if feels necessary.
