### ISSUE TITLE
Feature request: Scheduled payments - Ability to withhold a PKH's payments and then payout on a specific cycle.

### ISSUE THREAD

**Issue by steakandbake** [habanoz/tezos-reward-distributor#200]
**Is your feature request related to a problem? Please describe.**
For tax/accounting purposes, a delegator would like to pause their payments and then receive a lump sum transaction at a future date. 

**Describe the solution you'd like**
Add a rules_map rule where we can suspend their payments. For instance, a new (right side) TOPB could mean to pending balance. Changing TOPB to TOPB-345 could trigger paying their balance only on cycle 345. If the cycle has passed, their balance accumulates.

**Describe alternatives you've considered**
Maybe their's another easier way with trd I have not yet thought of?

**Comment by utdrmac** [comment]
I think a different option, one that showcases Tezos's on-chain abilities, would be to create a smart contract which can only be withdrawn from tz1 holder wishing to "pause" payments. The delegator indicates to you that they want payouts paused. Baker creates KT1 with contract and parameters. Code within contract only allows transfer out if delegator is the caller.

**Comment by steakandbake** [comment]
Genuinely great option. I will attempt that.

**Comment by utdrmac** [comment]
@steakandbake I kind of like the idea.  If you create the smart contract code, would you mind sharing it? We can include it within examples/ or even a contrib/ ?

**Comment by steakandbake** [comment]
Yes 🚀
