### ISSUE TITLE
calculation and payment error 

### ISSUE THREAD

**Issue by SemElVik** [habanoz/tezos-reward-distributor#24]
there is a duplication in the counting, but he does not count small delegates at all. Moreover, the 61st cycle counts correctly. and from 62-67nd is bad. 68+ is good again. 
another payment address was also tested, the result is the same.
 double calculation:  - https://ghostbin.com/paste/egdhb

UPD: file # tzscan_reward_api.py  - (MAX_PER_PAGE = 50)
-  i changed to 150  and he is not trying to repeat the calculation in a circle.
Now there is no double calculation. but apiTzScan itself counts only 50 accounts

**Comment by habanoz** [comment]
This is strange. I was pretty sure this was working. Has tzscan changed the way it worked? 

Anyways, I changed logic. Please update.

I am waiting for your confirmation before closing the issue.

**Comment by SemElVik** [comment]
Yes, it seems now the calculation is correct. thank you
