### ISSUE TITLE
Transfer fee is taken from delegators

### ISSUE THREAD

**Issue by utdrmac** [habanoz/tezos-reward-distributor#29]
**Describe the bug**
Delegator is awarded Y XTZ. When the transfer operation is created, the fee is deducted from Y. Delegator receives (Y - txnFee).

**Expected**
It is expected that delegators receive Y as their calculated reward.

**Implementation**
Give bakers the option to pay the transfer fee if they wish.

**Comment by habanoz** [comment]
Agreed. Merging and closing.
