### ISSUE TITLE
How should the rounding behavior be in the case of 0 fee ?

### ISSUE THREAD

**Issue by habanoz** [habanoz/tezos-reward-distributor#31]
Currently, payment amounts can have 3 decimal places. To achieve this, the payment amount is rounded down to 3 decimals.  

This effectively means that the minimum payment amount is 1 milli-tezos. This also eventually sets an implicit minimum delegation amount. (You may calculate the amount of tezos needed to obtain rewards that are at least one milli-tezos.) 

Event If fee ratio is 0 (either by setting standard_fee to 0 or adding an address to supporters_set), this policy is applied and the leftover amount is kept which creates the illusion of non-zero fee. 

Let's discuss how should rounding policy be in the case of 0 fees.

**Comment by habanoz** [comment]
My view is as-is should be preserved due to following arguments:
- I support the minimum payment amount policy for 0 fee customers. 
- The leftovers are tiny and can still be regarded as 0.
- If delegation is so small that the reward amount is less than 1 millis, the delegate may need to pay the transfer fee for nothing in return.

**Comment by nurikabe** [comment]
Probably a dumb question, but: Why is the min payment amount limited to 0.###?

**Comment by habanoz** [comment]
@nurikabe minimum payment amount is 1 milli-tezos. This is a choice made. It could have been a different amount, but I believe 1 milli-tezos is a fair amount. 

Please note that a large min payment amount may result in a significant deduction from delegators share. A tiny min payment amount on the other hand may result in transfers amounting less than transfer fee.

I believen It is a good practive to limit decimal places. It is present in payment systems dealing with fiat currencies. After 3 digits decimals makes no sense for the delegator but it makes calculations harder. 1.23+0.345 and 1.230123+0.345002. Former is more managable.

**Comment by nurikabe** [comment]
>> For example, in my case I want to change the minimum payout amount in dry-run mode to sanity check the numbers.

> Could you please provide some more details? I wish to understand how this will going to be useful.

I ran some dry runs to make sure the calculations made sense.  I was unaware of the rounding behavior; hence delegate calcualtions looked incorrect.  This resulted in #26.

At the very least I think this rounding behavior should be clealry documented.

Personally I would like to turn the rounding off so that I can more easily review the calculations.

Similarly I can imagine want to change this rounding level in the future.

**Comment by habanoz** [comment]
OK. Let's make rounding behavior documented and configurable. Let's give the option to close the rounding behavior.

**Comment by habanoz** [comment]
Closing this issue. Get update. Test. Feel free to re-open.
