### ISSUE TITLE
Aggregation of founder and owner payments with the same address

### ISSUE THREAD

**Issue by habanoz** [habanoz/tezos-reward-distributor#32]
**Describe the bug**
If same address is both founder and owner, two different transactions are done which means double transfer fee.
.
**Expected behavior**
Payments to the same address should be aggregated to a single payment. Reporting should remain separate.

**Comment by SemElVik** [comment]
it would be convenient.

**Comment by habanoz** [comment]
In V5 this is supported. A new type M which stands for MERGED is created. Merging is done at Phase6 : Merge Phase.
