### ISSUE TITLE
error in dry mode

### ISSUE THREAD

**Issue by SemElVik** [habanoz/tezos-reward-distributor#33]
**Describe the bug**

when I run the last cycle (64) in the dry mode, it gives an error. 
- address balance is positive.
- I am on the latest update.
 
`2019-02-03 21:39:05,371 - main - DEBUG - consumer0 - Running 71 operations
2019-02-03 21:39:05,809 - main - ERROR - consumer0 - Error at reward payment
Traceback (most recent call last):

  File "/home/t32/tezos-reward-distributor/src/pay/payment_consumer.py", line 70, in run
    payment_logs = batch_payer.pay(payment_items, self.verbose, dry_run=self.dry_run)
  File "/home/t32/tezos-reward-distributor/src/pay/batch_payer.py", line 79, in pay
    payments_log = self.pay_single_batch_wrap(payment_items_chunk, verbose=verbose, dry_run=dry_run)
  File "/home/t32/tezos-reward-distributor/src/pay/batch_payer.py", line 94, in pay_single_batch_wrap
    return_code, operation_hash = self.pay_single_batch(payment_items, verbose, dry_run=dry_run)
  File "/home/t32/tezos-reward-distributor/src/pay/batch_payer.py", line 155, in pay_single_batch
    error_desc = parse_json_response(runops_command_response)
  File "/home/t32/tezos-reward-distributor/src/util/rpc_utils.py", line 16, in parse_json_response
    raise Exception("Unknown client response format")
Exception: Unknown client response format`

**Expected behavior**
Reward Payment

**Environment**
 - Source Code Build
 - Chain mainnet
 - python3 src/main.py  -C 64  -M 3 -D  pay1

**Comment by habanoz** [comment]
Would you please run with verbose mode (-V) and share logs?

**Comment by SemElVik** [comment]
https://ghostbin.com/paste/mh8dvgfk

paste password -    `ds56[`

**Comment by SemElVik** [comment]
Unexpected server answer

**Comment by SemElVik** [comment]
It seems it was decided by itself.
I did not do anything. just checked again a little later.        
most likely there were problems with tzScan. although not exactly sure.

**Comment by habanoz** [comment]
I cannot correlate with tzscan. Error was within the payment phase. Can you look at the node log? You may see something useful there. Please note that it is not easy to locate the related node log section, because node logs a lot of stuff.

**Comment by SemElVik** [comment]
I'm not sure that I will find a log. but I I'll see.

**Comment by SemElVik** [comment]
not sure what you need.
node log looks like usual.
it was requested on two different nodes, with the same error response.

**Comment by habanoz** [comment]
> node log looks like usual.

Yeah, it is not easy to find information form node log. 

So, next time if you have a similar issue please have a quick look at the node log for relevant information. I do not your setup. 

I check node log like this which lists logs belonging to last 10 minutes:
```
journalctl --unit=tezos-node.service --since "10 min ago"
```

Or last 100 lines like this:
```
journalctl --unit=tezos-node.service -n 100 --no-pager
```

**Comment by SemElVik** [comment]
again the same error on the same billing address

**Comment by SemElVik** [comment]
after sending from my billing address to myself, I received another exception. 
```Traceback (most recent call last):
  File "/home/tz/tezos-reward-distributor-2/src/pay/payment_consumer.py", line 70, in run
    payment_logs = batch_payer.pay(payment_items, self.verbose, dry_run=self.dry_run)
  File "/home/tz/tezos-reward-distributor-2/src/pay/batch_payer.py", line 79, in pay
    payments_log = self.pay_single_batch_wrap(payment_items_chunk, verbose=verbose, dry_run=dry_run)
  File "/home/tz/tezos-reward-distributor-2/src/pay/batch_payer.py", line 94, in pay_single_batch_wrap
    return_code, operation_hash = self.pay_single_batch(payment_items, verbose, dry_run=dry_run)
  File "/home/tz/tezos-reward-distributor-2/src/pay/batch_payer.py", line 210, in pay_single_batch
    raise Exception("Signature '{}' length must be 64 but it is ".format(len(signed_bytes)))
Exception: Signature '98' length must be 64 but it is```

then I checked the dry mode, and lo and behold, everything worked out.  
I don’t understand what the problem sometimes is with the pay address.

**Comment by habanoz** [comment]
Looking at your exception i can say that client(or signer) generates a weird signature. Signature length must be 64 but it is 49.

Apart from that nothing makes much sense.

**Comment by SemElVik** [comment]
Yes, I see., and I do not know for the time being why so.
