### ISSUE TITLE
Error running the actual payout

### ISSUE THREAD

**Issue by issie81** [habanoz/tezos-reward-distributor#34]
I am running python3 src/main.py KTxx but the script gives me errors (see screenshot)
the KT1 address is pass encrypted during the run i never got question about the fill in my pass is that maybe the reason why this fails?

**Expected behavior**
Do the actual payment

**Screenshots**
![image](https://user-images.githubusercontent.com/35930081/52182319-3707a300-27fc-11e9-8a3e-374a699521e8.png)

**Environment**
 - Source Code Build
 - Chain mainnet
 - actual command used python3 src/main.py KTxx

**Comment by habanoz** [comment]
I see no way to provide password to the client. 

You have two options:
- You may use tezos-signer to provide signatures for you.
- You may create an unencrypted address for payouts.

**Comment by SemElVik** [comment]
`./tezos-client import secret key <name> unencrypted:<your-private-key>`

example: `./tezos-client import secret key payaddress unencrypted:edskS..........9KX`

**Comment by issie81** [comment]
@SemElVik i get error on that

/tezos$ ./tezos-client import secret key hoihoi unencrypted:edesk1bxxxxxxho
Disclaimer:
  The  Tezos  network  is  a  new  blockchain technology.
  Users are  solely responsible  for any risks associated
  with usage of the Tezos network.  Users should do their
  own  research to determine  if Tezos is the appropriate
  platform for their needs and should apply judgement and
  care in their network interactions.

Error:
  Failed to read a b58check_encoding data (Signature.Secret_key): "edesk1bxxxxxxho"

**Comment by SemElVik** [comment]
my key  -   edsk....

**Comment by issie81** [comment]
with what commando did you create the address

i dont mind making new address

**Comment by SemElVik** [comment]
Commands for managing the wallet of cryptographic keys 
https://tezos.gitlab.io/master/api/cli-commands.html 

- I did TezBox

**Comment by issie81** [comment]
yeah man i exported the unencrypted key by Tezbox superb!
and i allready made the payment for the cycle:))) 

like paying out with the KT1 adress did not go good

python3 src/main.py KT1xxx

i had to do python3 src/main.py payment_alias

is there a way to pay with KT1 adress the payment_alias is from the tz1 account where the KT1 is originated from... so i can top of the KT1 address with enough funds and delegate back to me with 0 funds... no good idea to keep on tz1

**Comment by habanoz** [comment]
KT1xxx should also work. If not please provide some logs. Using alias is preferred way.

I would suggest using tz addresses for payouts. However, in your case, I see your point. @SemElVikI remember you were trying to achieve a similar thing. How did it go?

Please be part of our community. It will be even better with you.

**Comment by issie81** [comment]
i will try this KT1 if i am unsuccesfull then nothing to do guess have to use Tz1

![image](https://user-images.githubusercontent.com/35930081/52196396-fe97b180-285b-11e9-9497-030cbd19901d.png)

this happens when using KT1 but switching to alias works unfortunatly you can not alias a KT1 (it is originated)

**Comment by SemElVik** [comment]
I did not manage to install KT as billing.
I did not understand how both keys are formed (KT+TZ) in theory, the key should be the same.  but I have not met the literature on KT address. 
at the moment, for now, I left the address tz.

**Comment by issie81** [comment]
ok Tz1 it is then

i have 3 questions left

1. i have one delegee he gets not much but his reward is negative why?

Reward created for cycle 67 address xx amount -0.576000 fee 0.671851 tz type D

2. are these 2 mandatory?
map of founder payment address and deposit owners map, i just filled in my bakers address

3. calculation are base on Tzscan is this safe? like what if tzscan has bug and they add a 0 to the rewards, cant it be calculated based on the node?

**Comment by habanoz** [comment]
> this happens when using KT1 but switching to alias works unfortunatly you can not alias a KT1 (it is originated)

In fact you can. You need to import origin contract before you can use originated contract for payments.

In order to import origin contract you can use import secret key command:
```
tezos-client import secret key new uri
```

In order to set alias to an originated contract you can use:
```
tezos-client remember contract new src
```

src being the KT address, new being the alias.

For more information you may refer to tezos command line interface doc.
https://tezos.gitlab.io/master/api/cli-commands.html

**Comment by habanoz** [comment]
If you want to make sure, try:

```
tezos-client list known contracts
```

**Comment by habanoz** [comment]
> i have one delegee he gets not much but his reward is negative why?

A negative reward is not expected. Can you share logs?

**Comment by habanoz** [comment]
> are these 2 mandatory?
map of founder payment address and deposit owners map, i just filled in my bakers address

Thanks to @utdrmac, they are not.

**Comment by habanoz** [comment]
> calculation are base on Tzscan is this safe? like what if tzscan has bug and they add a 0 to the rewards, cant it be calculated based on the node?

Tzscan dependency is questioned in #7 . However, it is not a minor thing to do. It demands a lot of time but provides very little in return. 

Tzscan API has been around for a while and has no sign to question its reliability. From availability perspective, it provides 6 mirrors.

RPC based reward calculations are expected in relaese 4. I can priotize it if I see more demand. Please do not hesitate to comment in #7.

**Comment by issie81** [comment]
# founders that shares the profits. map of founder payment address and share of the profit. Shares should sum up to 1.
founders_map={}
# deposit owners map of address and deposit ratio which must sum up to 1
owners_map={}
# no fee customers, e.g. founders, supporters

is this set like correct!!

and yeah i see the contract:)

which log do you want i have the log of the main.py but it doesnt specify any calculation?
i have calculations cvs? of 66 and 67

**Comment by SemElVik** [comment]
@issie81  open please  another rissue . you have everything in a bunch
