### ISSUE TITLE
Negative reward delegee

### ISSUE THREAD

**Issue by issie81** [habanoz/tezos-reward-distributor#35]
i have 2 negative payement for one delegee of 66 and 67 (both negative)

xx D	0.000280	0.083440	10.000000	-0.751000	0.834440
xx D	0.000090	0.095851	7.000000	-0.576000	0.671851

prior these cycles i did maybe to much paying (because of testing purposes and since its small payments no worry)... now i decided to stick with the reward distributor.. does the reward distributor look into past payments and make the future ones negative?

calculation are base on Tzscan is this safe? like what if tzscan has bug and they add a 0 to the rewards, cant it be calculated based on the node?

**Comment by habanoz** [comment]
> xx D	0.000280	0.083440	10.000000	-0.751000	0.834440
xx D	0.000090	0.095851	7.000000	-0.576000	0.671851

Sorry, does not make much sense. Can you share full log file.

The software does not check past payments. For the tzscan please see my response in your previous issue record.

**Comment by issie81** [comment]
where is this full log situated kind Sir?

**Comment by habanoz** [comment]
the application generates a file called 'app.log'. It can be found in the working directory. Also screen output is similar to the log file. You may also share it.

**Comment by issie81** [comment]
Due to privacy i send you complete uncensored log by mail

**Comment by issie81** [comment]
also i have other delegate with negative feed, just send new logging to you

**Comment by habanoz** [comment]
This looks like a service fee ratio problem. If you have your service fee %4.5 it should be set to 0.045.

Please adjust your settings.

**Comment by habanoz** [comment]
Closing this issue.
