### ISSUE TITLE
Purpose of owners and bond map

### ISSUE THREAD

**Issue by issie81** [habanoz/tezos-reward-distributor#36]
Currently BusinessConfiguration.py looks like on the owner and founder map

owners_map={}
founders_map={}

i dont use bondpool or something like this
i have a baker service and i am the owner of the baker.. will i loose something if i leave it blank

**Comment by habanoz** [comment]
Founders are who operate the bakery. Their reward comes from fee deducted from delegators. If the founders do not want any payment, leave it blank.

Owners are who own the staking balance. Their reward comes from bakings/endorsments made. Their difference from regular delegators is that they do not pay any fee to bakery. If owners do not want any payment you may leave it blank.

In most common case, founders and owners are the same set of people and they want to be paid.

**Comment by issie81** [comment]
i understand and if it's blank who gets the deducted fees from delegators?

**Comment by utdrmac** [comment]
If left blank, any remaining rewards are defaulted to the baker's TZ1 address
