### ISSUE TITLE
Make ratio roundings configurable

### ISSUE THREAD

**Issue by moonrider-unchained** [habanoz/tezos-reward-distributor#37]
Tested this tool and found an issue that payment amounts are slightly different from my own calculations. Then I dig into this issue and found that the reason is delegator's `ratio` rounding error. For example, one of my clients's share is `20.4401061108447%` and cycle rewards is `474.382585 XTZ`
But your tool rounds share to `20.44%` and attempts to pay a little bit less - only `474.380121`

So here are 2 questions:
1. Maybe let's expose ratio rounding setting to the config? 
Default value could be `5`, but personally I'd like to increase  this value to let's say `10` so rewards payments will be more precise.

2. As for now, is it enough to change `ratio = round(balance / effective_delegate_staking_balance, 5)` to let's say `ratio = round(balance / effective_delegate_staking_balance, 10)` in tzscan_rewards_calculator.py?

**Comment by moonrider-unchained** [comment]
Found out that setting `ratio = round(balance / effective_delegate_staking_balance, 10)` in `tzscan_rewards_calculator.py` and pymnt_scale = None` in `BusinessConfigurationX.py` solves the issue

**Comment by SemElVik** [comment]
Oh yeah. I checked in the same way. Now everything is as it should be. fine @moonrider-unchained

**Comment by habanoz** [comment]
This is fair. I added prcnt_scale parameter to BusinessConfigX file.
