### ISSUE TITLE
Ability to provide payments on another (custom) address

### ISSUE THREAD

**Issue by moonrider-unchained** [habanoz/tezos-reward-distributor#39]
Real business case:
- Client moved his stack to a ledger and asked to pay his rewards to the new address.

Solution required:
- Ability to set custom payments addresses for existing deleguees.

**Comment by habanoz** [comment]
payment address and baking address: they already separate. 

Payment address is given from command line.

**Comment by moonrider-unchained** [comment]
I mean the ability to pay to another address. 
Imagine that I have a client that delegates from his address `KT1aaa`
Now he decided to move funds to his ledger with address `KT1bbb` and asked to pay to his new address `KT1bbb` instead of his old `KT1aaa`
So would be nice if I can map such deleguees and pay to a custom address:
{“KT1aaa”: “KT1bbb”}
Which means “Pay rewards of `KT1aaa` to `KT1bbb`”

**Comment by habanoz** [comment]
In V5 this is supported. Use rules_map config option to specify the target address. See examples/tz1boot1pK9h2BVGXdyvfQSv8kd1LQM6H889.yaml for an example.
