### ISSUE TITLE
Ability to calculate owners and founders share, but not actually pay it

### ISSUE THREAD

**Issue by moonrider-unchained** [habanoz/tezos-reward-distributor#40]
**Is your feature request related to a problem? Please describe.**
I want to see how much I get from fees and baking separately, but do not provide payments to founders/owners - it's equals to paying to myself. 

**Describe the solution you'd like**
Would be nice to have an ability to set `calculate_only_owners_and_founders_rewards = true` - show fees and baking rewards of the baker separately in calculations csv report, but do not create payments.

**Comment by habanoz** [comment]
In V5 this is supported. Just leave founders and/or owners empty.
