### ISSUE TITLE
Cant payout from KT1 address

### ISSUE THREAD

**Issue by issie81** [habanoz/tezos-reward-distributor#42]
As reported making payment from KT1 fails.

i imported the unencrypted key with 

./tezos-client import secret key <name> unencrypted:<your-private-key>

and after this i run

./tezos-client remember contract new src

both are in alias as show when run

./tezos-client list known contracts

yet i can only send with tz1 alias

also note that i figured out sending funds if the tz1 is not set as delegate it does give error, i just imported new key the tz1 didnt work after running this it worked (maybe handy to put into documentation)

./tezos-client register key tz1alias t as delegate

**Comment by habanoz** [comment]
Fixed in V3.

**Comment by SemElVik** [comment]
really seems to work in (v3).
I remembered the billing address contract tz., gave a alias to the KT address, checked the new contract.

then set the KT billing address to the .yaml configuration file
- in the dry mode, there were no errors
