### ISSUE TITLE
More and better reports

### ISSUE THREAD

**Issue by issie81** [habanoz/tezos-reward-distributor#43]
Is there way to get more and better reports.. like maybe a json file where everything is stated like this, we can use this as for the dashboard:

  "64": {
            "delegators": {
                "xx": {
                    "balance": "142380600",
                    "estimatedRewards": "191041",
                    "finalRewards": "191056"
                }
            },
            "estimatedBakerRewards": {
                "bondRewards": "15787731",
                "feeRewards": "21226",
                "looseRewards": "2",
                "totalRewards": "15808959"
            },
            "estimatedTotalRewards": "16000000",
            "fee": {
                "denominator": 10,
                "numerator": 1
            },
            "finalBakerRewards": {
                "bondRewards": "15788989",
                "feeRewards": "21228",
                "looseRewards": "2",
                "totalRewards": "15810219"
            },
            "finalTotalRewards": {
                "estimatedDifference": "-1275",
                "paid": "16001275",
                "realized": "16001275",
                "realizedDifference": "0"
            },
            "stakingBalance": "10732128232",
            "stolenBlocks": []
        },
        "65": {
            "delegators": {
                "xx": {
                    "balance": "142380600",
                    "estimatedRewards": "71640",
                    "finalRewards": "71640"
                }

also since the current system is working with tz1 accoount which needs to be topped out good, we need to know how much has to sit on the account would be great if we got report how much we need to pay for the delegees since there is 5 day frozen period and stuff this should easily be put in repor like

cycle xx payouts 666
cycle xx payouts 666
cycle xx payouts 666
cycle xx payouts 666

would be great if also you can specify including or excluding founder and deposit map

last but not least Sir Huseyin i think your doing fantastic job
do you accept donations, would love to donate for your efforts

**Comment by habanoz** [comment]
The JSON format you shared is very specific. Can you give more information about your dashboard? Is it open source? Can you modify it to read csv files?

Tzscan shows how much will be paid for next 6 cycles, below staking balance section. Is not this enough?

**Comment by habanoz** [comment]
In V5 CSV reports are improved. Please have a look at them. Application logs are also improved.
