### ISSUE TITLE
Set Freezecycle

### ISSUE THREAD

**Issue by issie81** [habanoz/tezos-reward-distributor#44]
Hello Sir,

sorry to spam the Github, but i see on mainpage github this,

freeze cycle: number of cycles rewards are kept frozen by the tezos network. Can be given negative values to let the application make future payments.

if i want to pay the delegees instant without 5 cycle freeze this valua should be -5 i assume?

Where would one define this value?, i looked around abit couldnt find it

**Comment by SemElVik** [comment]
-D means dry run
-Dn means do not run payment worker
-R is release override

python3 src/main.py -D -Dn -R -5 -M 3 -C 74 <paymentaddress> 
- play with the cycle you need

**Comment by issie81** [comment]
nice one man i really love this tool, why would one use -Dn? @SemElVik

**Comment by SemElVik** [comment]
will not start the payment, only the calculation

**Comment by issie81** [comment]
so i did -R5 i paid 4 cycles one has failed (70), when i run a single run with -C 70 (without -R -5)
i get this

No pending payments for cycle 70, current cycle is 74

i saw in map dry payments i had 70 in file done and 70 in map failed both i deleted so the cycle re-run, why do i get my pending payments for cycle 70

@SemElVik

**Comment by SemElVik** [comment]
play with the cycle! 
`python3 src/main.py -D -Dn -R -11 -M 3 -C 79`    -    count for 79 cycle.   
68 (last paid)+11 = 79 
TzScan counts 5 cycles ahead.  80 cycle you will not count

**Comment by SemElVik** [comment]
if you count 74-79 then these cycles have not yet been baked. be careful with this.

**Comment by issie81** [comment]
@SemElVik but my cycle 70 failed, when i want to run again lets say

python3 src/main.py -M 2 -C 70 alias

the output is

DEBUG - producer  - No pending payments for cycle 70, current cycle is 74

yet this cycle is not paid, how can i paid, where is it logged it's paid?

69, 71, 72, 73 went good
(maybe because 5 cycles in one day handled differently)

**Comment by SemElVik** [comment]
I will assume that in the 70th cycle there were no awards

**Comment by issie81** [comment]
i just checked on tzscan, there were

**Comment by SemElVik** [comment]
`python3 src/main.py -D -Dn -R -2 -M 3 -C 70 <alias>`

**Comment by issie81** [comment]
@SemElVik your a legend!!

still dont get why this didnt work:)

python3 src/main.py -M 2 -C 70 flippintacos

**Comment by habanoz** [comment]
Formula for last released cycle is: 
current_cycle-(NB_FREEZE_CYCLE+1)-release_override

If -R is not given it is 0. Right now current cycle is 74:
74-6=68 is the last released cycle. You cannot pay beyond this cycle. 

If you want to pay for let's say 73; you need to make a simple calculation:
73 =  current_cycle-(NB_FREEZE_CYCLE+1)-release_override = 74-6- release_override 
release_override = 74-6-73 = -5 

You need to set -R -5 to make payment for cycle 73. 

-
If you set -R smaller than -5 you will start to pay for un-baked cycles. You may fail to bake them.

**Comment by issie81** [comment]
superb!
