### ISSUE TITLE
Linux Service error

### ISSUE THREAD

**Issue by MarimbaTz** [habanoz/tezos-reward-distributor#50]
Running the `sudo python3 service_add.py paymentaddress`  is printing the following error: Failed to enable unit: Unit file tezos-reward.service does not exist.
But the `tezos-reward.service` file is generated and inside the `tezos-reward-distributor` folder.

**Comment by habanoz** [comment]
Please update your code. V3 does not require a payment address. It is read from yaml configuration file.

**Comment by habanoz** [comment]
Closing, due to inactivity. You may reopen.
