### ISSUE TITLE
Signing Failure Errors

### ISSUE THREAD

**Issue by nurikabe** [habanoz/tezos-reward-distributor#53]
**Is your feature request related to a problem? Please describe.**
Maybe this is a feature request.

Updates to rounding configuration in #31 made dry run tests super clear.  Thanks for that.

I finally went to run the reward-distributor (V2.1) for real, but it seems to fail silently when making payments.  I gueeeesssss(?) this is because I would have to enter a password for my private key to sign the transactions.

**Describe the solution you'd like**
Would be helpful if the reward-distributor could somehow determine if it is able to sign transactions or, if not, show an appropriate error message.

**Describe alternatives you've considered**
Going to try running the signer.  Wondering how other people are doing this?  Are most running the signer, or living dangerously with unencrypted private keys?

**Comment by nurikabe** [comment]
Using the signer works as expected.

**Comment by habanoz** [comment]
V3 makes a check at startup. If private keys are not imported it fails with an error.

Anyone who considers using unsigned accounts for payments should not leave a considerable amount of tezos at that account. 

Example output from V3.
---
```
  File "/home/ubuntu/tezos-reward-distributor/src/config/yaml_baking_conf_parser.py", line 126, in check_sk
    raise ConfigurationException("No secret key for Address Obj {} with PKH {}".format(addr_obj, pkh))
exception.configuration.ConfigurationException: No secret key for Address Obj {'pkh': 'tz1aZoYGSEoGpzWmitPaCJw6HQCkz5YSi1ow', 'originated': False, 'alias': 'mainpay', 'sk': False, 'manager': 'tz1aZoYGSEoGpzWmitPaCJw6HQCkz5YSi1ow'} with PKH tz1aZoYGSEoGpzWmitPaCJw6HQCkz5YSi1ow
```

In V2, it was necessary to use aliases when using accounts signed with signer. In V3, it is not necessary aynmore. V3 also makes it possible to pay with KT addresses. 

Closing this issue, you may reopen anytime.
