### ISSUE TITLE
Update README for new users

### ISSUE THREAD

**Issue by utdrmac** [habanoz/tezos-reward-distributor#56]
The README does not give proper instructions to new users. The v3 migration is for users that are migrating and talks about creating the  ~/pymnt/cfg/ directory. But the README does not discuss this. So new users (ie: non-migrating users) may be lost in setting up.

**Comment by habanoz** [comment]
Agreed. I will change README or add a wiki page for this. 

Migration procedure will be removed. It is provided for those use V2. New users will start with V3.

**Comment by habanoz** [comment]
Readme and example config file updated. Closing this issue but The repo is open to new documentation enhancements.
