### ISSUE TITLE
V3 Specials ratio is broken

### ISSUE THREAD

**Issue by habanoz** [habanoz/tezos-reward-distributor#58]
V3 specials_dict ratios are not used correctly. Whole calculations are messed up. Yielding negative payments. Negative payments are expected to be rejected. As a result, I do not expect any negative impact.

Please update asap.

**Comment by habanoz** [comment]
The issue is fixed upon detection. Please update.

**Comment by SemElVik** [comment]
never noticed negative values.
OK, updated.
