### ISSUE TITLE
Setting supporters/specials to empty results in crash

### ISSUE THREAD

**Issue by utdrmac** [habanoz/tezos-reward-distributor#6]
**Describe the bug**
We have no supporters and no specials. So we set the parameter as empty.
```
supporters_set={}
specials_map={}
```

```
Traceback (most recent call last):
  File "src/main.py", line 413, in <module>
    main(args)
  File "src/main.py", line 311, in main
    full_supporters_set = supporters_set | set(founders_map.keys()) | set(owners_map.keys())
TypeError: unsupported operand type(s) for |: 'dict' and 'set'
```

**To Reproduce**
See above

**Expected behavior**
Expected the code to handle empty sets when there are no specials/supporters

**Environment**
6ec9f4c4d03c5e55016db9ae5a611ac7427255c5
alphanet
`$ python36 src/main.py -D -N ALPHANET tz1LdZ6S8ScNMgaCLqrekDvbBWhLqtUebk23`

**Comment by utdrmac** [comment]
Commenting out either line results in the following:

```
Traceback (most recent call last):
  File "src/main.py", line 10, in <module>
    from BusinessConfiguration import BAKING_ADDRESS, supporters_set, founders_map, owners_map, specials_map, STANDARD_FEE
ImportError: cannot import name 'supporters_set'
```

**Comment by utdrmac** [comment]
Had to go learn some quick python. This made things work:

```
supporters_set=set()
```

**Comment by habanoz** [comment]
Required changes are made. supporters_set may be left empty. 

Closing the issue. If the problem persists, you may open it again.

**Comment by habanoz** [comment]
The legitimate way to leave supporters_set empty is the intuitive one:

supporters_set={}
