### ISSUE TITLE
Cannot make it work by following the readme

### ISSUE THREAD

**Issue by nicolasbronstein** [habanoz/tezos-reward-distributor#61]
Steps to reproduce:

1- Generate new account for payments, call it "paythebill", now if I do: ./tezos-client show address paythebill -S, I get this:

Hash: tz1...
Public Key: edpkte...
Secret Key: encrypted:edes...

2- Top up the account and reveal it (not sure why you need to reveal it, but done!)

3- Follow the readme and try dry run, it seems to work, then try normal and I get to this point:

date - main - INFO - producer  - Run mode PENDING satisfied. Killing the thread ...
date - main - INFO - producer  - Producer returning ...
date - main - INFO - MainThread - Interrupted.
date - main - INFO - MainThread - --------------------------------------------------------
date - main - INFO - MainThread - Sensitive operations are in progress!
date - main - INFO - MainThread - Please wait while the application is being shut down!
date - main - INFO - MainThread - --------------------------------------------------------

...
where it stays forever locked... by pressing ctrl+C to kill it I got that it was waiting for the password to be written, I tried that at that point but then it fails because the payload it tries to send has the "signature":"Enter password for encrypted key: Signature: edsigt...." payload when trying to post the RPC call...

how do I do in order to avoid entering the password each time? I looked all over the tezos-client documentation but couldn't find a way to do just that...

**Comment by SemElVik** [comment]
create an unencrypted key. 
`./tezos-client import secret key <alias> unencrypted:<your-private-key> `

**Comment by nicolasbronstein** [comment]
> create an unencrypted key.
> `./tezos-client import secret key <alias> unencrypted:<your-private-key> `

thanks, this is what I'm looking for, however, how do I put in the  "your-private-key" part if what I have is the "encrypted" version of it?

**Comment by nicolasbronstein** [comment]
and on another note, couldn't this application ask for the password and use it while it is running? I'd rather input the password and keep it in memory to decode the encrypted version than storing the unencrypted version of one

**Comment by nicolasbronstein** [comment]
so I got it working, tezbox did the trick, imported the encrypted version and revealed the unencrypted one once inside, now is working, I'd implement the above however if possible, I think you can make it work like that... Something else that I had to do that is not in the readme was to modify the master.yaml file to import my keys into the client (spent a good amount of time figuring out that error)... thanks for your work mate, very nice little piece of repo here, have a star!

**Comment by habanoz** [comment]
Added additional descriptions to the readme. Consider use of tezos signer for security and to avoid password typing. 

Currently, use of master.yaml is not adviced. It serves testing only.

**Comment by nicolasbronstein** [comment]
Only by adding the addresses there in the master.yaml file I managed to go past the "import them first to the client" error that I get when launching the service and with a known key registered in the tezos-client, how should that be done instead?

**Comment by habanoz** [comment]
Can you remove master file and share the full log file?

**Comment by nicolasbronstein** [comment]
Just did, removing the master.yaml file is enough so that the issue does not occur, I'd suggest to add that to the readme, or put it on a feature branch so that it does not bother while under development. Thanks for your work!
