### ISSUE TITLE
PRESERVED_CYCLES in Alphanet

### ISSUE THREAD

**Issue by amzid** [habanoz/tezos-reward-distributor#63]
The current network configuration suggests that NB_FREEZE_CYCLE is equal to two in the Alphanet network.
However, when executing the following command for preserved cycles:
`curl -s https://rpcalpha.tzbeta.net/chains/main/blocks/head/context/constants | jq .preserved_cycles`,
the obtained constant is equal to three.
I think the network configuration should be reviewed, and adjusted to be acquired dynamically from the node.

**Comment by habanoz** [comment]
This could be obtained from the node service. A community member can volunteer to create this and send PR. Please review the contribution guide beforehand. 

Please note that TRD is designed to work in environments without node service. So PR should take parameters from constants if a node service is not accessible.

**Comment by amzid** [comment]
I would suggest the following:
**First** if a local node service is accessible, then the network configuration constants should be set through a rpc local access.
**Otherwise** try to set the constants from a public node access, such as `https://rpcalpha.tzbeta.net/chains/main/blocks/head/context/constants`
**Otherwise** if both possibilities above are not accessible, then the constants should be set from a predefined set of constants in Constants.py, which should be updated in a regular basis.

Is acquiring the network configuration from a node expected to be implemented in the file model/network_configuartion.py, or is this file used for another purpose?

**Comment by habanoz** [comment]
Use of public nodes is a good idea. 

> First if a local node service is accessible, then the network configuration constants should be set through an RPC local access.

This could be done. Also, this step could be skipped. Network constants tend not to change too often, so it is not necessary to put a lot of effort to track them. I leave the choice to the implementer. Please note that TRD already has arguments to specify RPC URL. 

> Otherwise try to set the constants from a public node access, such as https://rpcalpha.tzbeta.net/chains/main/blocks/head/context/constants

Yes. Just make sure the correct network is selected e.g. zeronet, alphanet, mainnet. 

> Otherwise if both possibilities above are not accessible, then the constants should be set from a predefined set of constants in Constants.py, which should be updated in a regular basis.

src/NetworkConfiguration.py contains a dictionary named "network_config_map". This map contains network constants. Those values are already being used. If a local or public node access is made, It is enough to modify those values with those taken from the node. 

src/model/network_configuartion.py is not used. It could be removed. Another idea could be to alter network_config_map to be a dictionary of network_name:NetworkConfiguration pairs. Either way can be used, I would suggest the easier one.

**Comment by habanoz** [comment]
This is implemented by @amzid . It will be merged with the next release.

**Comment by habanoz** [comment]
Code is merged. Closing.
