### ISSUE TITLE
Total Rewards Calculation and Denunciation

### ISSUE THREAD

**Issue by amzid** [habanoz/tezos-reward-distributor#64]
In the following calculation of the total rewards (to be found in tzscan/tzscan_reward_calculator.py): ![total_rewards_calculation](https://user-images.githubusercontent.com/33556352/54607145-ecf61c00-4a4d-11e9-8f99-6c230a3fbae3.png)
I expected the **lost rewards from denunciation** and **lost fees from denunciation** to be subtracted from the total amount of rewards.

And also if e.g. due to a double baking process, the baker looses the frozen deposits in that cycle, so that ultimately the total gain from that cycle (for the balance of the baker) is negative, should the lost deposits be considered in the calculation of the total rewards (i.e. subtract one more term which is **lost_deposit_from_denunciation**) or should the total amount of rewards be completely independent of any potential lost deposits?

**Comment by habanoz** [comment]
My view is, lost deposits should not be part of total rewards while lost rewards/fees should be. 

Because, I believe loss of deposit is completely at the responsibility of the baker. Delegation is the act of leaving the risk to the baker at the cost of some portion of the baking reward.

**Comment by habanoz** [comment]
Code merged. Closing.
