### ISSUE TITLE
FR: Minimum payout

### ISSUE THREAD

**Issue by utdrmac** [habanoz/tezos-reward-distributor#67]
**Is your feature request related to a problem? Please describe.**
We have many small delegations to our baker. Many times, the payout to the delegatee is < 0.1 XTZ. While it doesn't hurt us, seems like it should be better to wait until delegatee has at least X in rewards before sending.

**Describe the solution you'd like**
Implement "minimum payout" setting. During payments for cycle X, if delegatee would be paid < minimum, queue their payment (somehow) and wait for cycle X+1. On X+1, add queued amount (if any) to each delegatee during X+1 payments calculations. If < minimum, add to queue. If >= minimum, send payment and clear queues.

This may require some lightweight localized database file to store state (the queues):
-   https://github.com/zopefoundation/ZODB
-   https://github.com/msiemens/tinydb

**Describe alternatives you've considered**
None at this time.

**Comment by SemElVik** [comment]
```baking_address: tz-------------
excluded_delegators_set: {}
founders_map:
  .....................
min_delegation_amt: 0.0
owners_map:
  .....................
payment_address: ktpay
prcnt_scale: None
pymnt_scale: None
service_fee: 10.0
delegator_pays_xfer_fee : False
specials_map: {}
supporters_set: {}
version: '1.0'```

with this config, I pay even less than 0.0001 (1 μꜩ if exactly)

**Comment by SemElVik** [comment]
![2019-04-01_15-58-53](https://user-images.githubusercontent.com/27207809/55329442-3eaf9500-5497-11e9-9746-8b92eb39b9d6.png)

**Comment by utdrmac** [comment]
@SemElVik So do you consider this a non-issue then? I guess this is more of an issue for those bakers that pay the transfer fee themselves rather than taking it out of the delegatee's reward. You're paying the same transfer fee each time, for micro payments, or pay the fee one time, every 5 or so cycles (once delegatee has accumulated min amount).

**Comment by SemElVik** [comment]
it's not a problem for me to pay a commission.

I pay the transfer fee and the delegate gets what he baked with us to the penny.

but, if you remove the payment of the transfer fee and leave it for the delegate, then yes, he will not receive small payments.

**Comment by habanoz** [comment]
I acknowledge this as an issue. I believe It is not a good idea to pay commissions for payments less than commission itself. The simplest approach would be to set a minimum delegation amount.

**Comment by habanoz** [comment]
This feature can be implemented with one of the alternatives @utdrmac proposed. Another option could be using files as it is done with payment reports. Either way or another way it is going to make the application more complex. 

How this feature will be activated? It will need another configuration switch.  

Where should those files be kept? It will need to be configurable which will introduce new configuration parameters. 

If a baker moves the machine he will need to move the state files even he never uses them. This should be avoided for those who never use the feature. 

This feature is queued. Anyone willing to implement this can volunteer. We can discuss possible solutions.

**Comment by dansan566** [comment]
In my opinion, setting the minimum delegation to 1ꜩ, or 5ꜩ is not sufficient.

The baker earnings should be greater or equal the minimum transaction fee: 
Baker Fee * (Minimum Delegation Amount * Yield per Cycle) >= Minimum Transaction Fee

**Example:**
Minimum Delegation Amount >= 0,001274 / (0,1*(0,0551/~128) 
Minimum Delegation Amount >= 30 

I used the inflation (5,51%) and 128 Cycles in my calculations. The minimum fee is 0,001274 and the baker fee 10%. This is just an example of how we came it with a minimum delegation amount.

**Comment by utdrmac** [comment]
@dansan566 The math is easy. The bigger issue is how do you track non-payouts over a period of many cycles? For example, say your payout minimum is 10XTZ and you have a delegate that is earning about 3XTZ per cycle. Cycle X comes and he earns 3;  no payment. You must now track this reward somewhere. Cycle X+1. Another 3. Their total so far is now 6XTZ earned but still below 10 for payout. Cycle X+2, repeat. X+3 they now have earned 12XTZ, send pay out.

**Comment by jdsika** [comment]
hm, actually I would make the rule:
"If a payment is less then MINIMUM_PAYOUT it is rewarded to the baker" 

-> You just have to be transparent with it?

**Comment by dansan566** [comment]
@utdrmac You have set a minimum delegation amount and not a minimum payout in my example. There is currently a trade-off between the baker pays the transaction fee and a minimum delegation amount. I would be very careful with a minimum payout because someone could say your payouts are not correct. You also should not forget that the delegate is missing compound interest for the time you keep it.

**Comment by dansan566** [comment]
@jdsika I think it's easier to communicate a minimum delegation amount rather than "your fee which you have to pay for has to be greater than the minimum transaction fee".

**Comment by habanoz** [comment]
@dansan566 Maybe we should review your calculations. I believe you should user (1-baker_fee), obviously because this is delegator's share. Eventually, minimum delegation amount should be around 3.3 tezos.

I agree, minimum delegation amount policy is easy to understand and solves many problems.

**Comment by jdsika** [comment]
@utdrmac should we close this issue because the "minimum delegation amount" can be configured? Do you think it is necessary to "stack up" mini payouts owed and transfer them to a customer until it is higher then a certain threshold? It is a very complicated process which brings not so much value. Everybody should understand that putting 0.1€ in the bank might lead to more work then value :)

**Comment by utdrmac** [comment]
Probably can close. Hasn't been an issue for us. I was thinking that it would save on trx fees, but we subtract trx fees from payouts so, doesn't hurt us if your payment is tiny. However, if you were a baker that paid the trx fees, then this could save you xtz in the long run. Instead of 100 trx which each need 0.001793xtz as fee, you bundle up 100 into 1 and pay the fee only once.
