### ISSUE TITLE
FR: Remove dependency on tzscan

### ISSUE THREAD

**Issue by utdrmac** [habanoz/tezos-reward-distributor#7]
**Describe the solution you'd like**
All functionality of this application is dependent on tzscan.io. If tzscan is down, or inaccurate, or delayed, this tool carries the same issues.

**Describe alternatives you've considered**
This application should be using the local node's RPC-API to collect information.

**Additional context**
As of this posting, alpha.tzscan.io is incompatible with the new 003 protocol and is not showing accurate data. Because this application is dependent on data from tzscan, no testing using this app can happen at this time on alphanet.

**Comment by habanoz** [comment]
Your concerns are valid. However, use RPC API requires a lot of programming/testing effort. I need to see more demand before adding RPC based reward calculations.  

I will leave this issue open to see if there will be more demand.

**Comment by goodpen** [comment]
+1

**Comment by utdrmac** [comment]
What needs to be fetched from RPC?

- List of delegators
- list of 'active' delegators
- Balance of each delegator
- Staking balance of baker
- total balance of baker

The hardest thing I cannot find is for which cycle a delegator activates.

```
# Alphanet
$ ./tezos-client rpc get /chains/main/blocks/head/context/delegates/tz1LdZ6S8ScNMgaCLqrekDvbBWhLqtUebk23
{ "balance": "13594924319", "frozen_balance": "0",
  "frozen_balance_by_cycle": [], "staking_balance": "32345701585",
  "delegated_contracts":
    [ "KT1WyMWHxGt8HLgWG9LZEqxG5u2kEpHNyE8D",
      "KT1Ua68oUfTwykAC8MRh8JZm9Ekd8wp57rm9",
      "KT1MTZGjAZo9ZYNU2y72vxwpg3iqGUWpZyfm",
      "KT1Lg9R2b2UjJhJdhvRnNovdpaQF41o2jvgw" ],
  "delegated_balance": "18750777266", "deactivated": false,
  "grace_period": 7 }
```

You can see a list of all delegates but no info on their staked balance, nor any indication to which cycle their delegation amount unfreezes and becomes part of the staked balance. This is typically 7 cycles, but I was expecting there to be an RPC call to find out which specific block/level.

**Comment by utdrmac** [comment]
This RPC validates the KT1 is a delegate of our baker, tz1LdZ, and gives us the staked balance.

```
./tezos-client rpc get /chains/main/blocks/head/context/contracts/KT1XfTzTJWFMsEukKXXVoKbwsBFbZvYS3hkn
{ "manager": "tz1Sfe7Nm2MdmkCopA7DVBUHHEd8G73TWwfN",
  "balance": "14378132380", "spendable": true,
  "delegate":
    { "setable": false, "value": "tz1LdZ6S8ScNMgaCLqrekDvbBWhLqtUebk23" },
  "counter": "0" }
```

**Comment by habanoz** [comment]
/chains/main/blocks/head/context/delegates/<pkh>
balance + delegated_balance - rewars = staking_balance.

For a specific block we will need to use blockhash instead of 'head'. In order to get that we will need to find snapshot chosen for a cycle.

**Comment by utdrmac** [comment]
Been looking for snapshot information in RPC. Not documented fully.

**Comment by habanoz** [comment]
Yeah, documentation is not great. 

/chains/main/blocks/head/context/raw/json/rolls/owner/snapshot/<cycle>

returns selected snapshot index <sn_idx> for <cycle>

block index for which snapshot taken can be calculated. Remember in each block there are 16 snapshot thus 256 blocks between snapshots. Eventually:

block_index = sn_idx*256 + <cycle> * 4096

This block_index can be converted to block_hash. Once we have block hash we can query delegators/stake state for the specific block.

**Comment by utdrmac** [comment]
So this gives me snapshots I can access:
```
$ ./tezos-client rpc get /chains/main/blocks/head/context/raw/json/rolls/owner/snapshot
[ 7, 6, 5, 4, 3, 2, 1, 0 ]
```

Then I can query a specific (the current) cycle:
```
$ ./tezos-client rpc get /chains/main/blocks/head | jq -r '.metadata.level.cycle'
2
$ ./tezos-client rpc get /chains/main/blocks/head/context/raw/json/rolls/owner/snapshot/2/
[ 0 ]
```

What does that 0 mean here?
If I look at mainnet, current cycle 51:
```
https://rpc.tezrpc.me/chains/main/blocks/head/context/raw/json/rolls/owner/snapshot/51/
"[1]"
```

Fetching that:
```
$ ./tezos-client rpc get /chains/main/blocks/head/context/raw/json/rolls/owner/snapshot/2/0/
[ 2403, 2147, 1891, 1635, 1379, 1123, 867, 611, 2659, 355, 99, 2402, 2146,
  1890, 1634, 1378, 1122, 866, 610, 2658, 354, 98, 2401, 2145, 1889, 1633,
...
```

Fetching one of these:
```
$ ./tezos-client rpc get /chains/main/blocks/head/context/raw/json/rolls/owner/snapshot/2/0/596/
"p2pk66EmFoQS6b2mYLvCrwjXs7XT1A2znX26HcT9YMiGsyCHyDvsLaF"
```

And that is?

**Comment by habanoz** [comment]
How long does 

 ./tezos-client rpc get /chains/main/blocks/head/context/raw/json/rolls/owner/snapshot/2/

take on your mainnet node?

**Comment by utdrmac** [comment]
https://rpc.tezrpc.me/chains/main/blocks/head/context/raw/json/rolls/owner/snapshot/55/
Takes about 10 seconds

**Comment by utdrmac** [comment]
Found it. Credit to @DefinitelyNotAGoat [golang tezos](https://github.com/DefinitelyNotAGoat/go-tezos) library.

The pattern:
  - get level for cycle X (cycle X * 4096 + 1)
  - get block for level (/chains/main/blocks/" + headHash + "~" + (current level - level))
  - get roll snapshot index for block (/chains/main/blocks/" + block.Hash + "/context/raw/json/cycle/" + strCycle)
  - get snapshot block for payment cycle X (((cycleX - 7) * 4096) + (RollSnapShot+1)*256)
  - get staking balance of delegate using snapshot block (/chains/main/blocks/" + snapshot block 
 hash + "/context/delegates/" + delegatePhk + "/staking_balance)
  - get delegates at cycle X (/chains/main/blocks/" + snapshot block hash + "/context/delegates/" + delegatePhk + "/delegated_contracts
  - get rewards for delegate at cycle X (/chains/main/blocks/head/context/raw/json/contracts/index/" + delegatePhk + "/frozen_balance/" + X
  - foreach delegates, get delegate balance at snapshot (/chains/main/blocks/" + snapshot block hash + "/context/contracts/" + delegate KT1 + "/balance"
  -- calculate % of total staking per delegatee
  -- calculate reward for delegatee

**Comment by utdrmac** [comment]
The block-snapshot calculation is different on alphanet

```
PRESERVED_CYCLES=3
BLOCKS_IN_CYCLE=2048
(cycle - PRESERVED_CYCLES - 1) * BLOCKS_IN_CYCLE) + (snapShotQuery.RollSnapShot + 1) * 256
```

**Comment by habanoz** [comment]
Any idea why it is different? Reserved cycles parameter is already different in alpha and mainnet e.g. 2 vs 5.

**Comment by issie81** [comment]
+1 add dependance on the node

**Comment by habanoz** [comment]
@amzid implemented this feature.

**Comment by habanoz** [comment]
Work of @amzid is merged. Now RPC based calculations are supported.
