### ISSUE TITLE
Better exception handling on 502

### ISSUE THREAD

**Issue by utdrmac** [habanoz/tezos-reward-distributor#75]
When using tzscan and their API is down:

```
2019-04-24 17:04:12,369 - main - DEBUG - producer  - Trying payments for cycle 94
Exception in thread producer:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/bakebaker/tezos-reward-distributor/src/pay/payment_producer.py", line 82, in run
    current_level = self.block_api.get_current_level(verbose=self.verbose)
  File "/home/bakebaker/tezos-reward-distributor/src/tzscan/tzscan_block_api.py", line 42, in get_current_level
    raise TzScanException('GET {} {}'.format(uri, resp.status_code))
exception.tzscan.TzScanException: GET https://api6.tzscan.io/v2/head 502
```

502 should probably just produce an error message rather than displaying an exception/stacktrace. 502's from tzscan happen at least once a day, even on some of my other scripts that utilize their API.

**Comment by utdrmac** [comment]
Ok. Super serious issue now. This **HALTED** all operations. We missed payments. Had to restart.

**Comment by habanoz** [comment]
More information? Failed due to tzscan?

**Comment by utdrmac** [comment]
Yes. tzscan API returned http error code 502. this halted TRD. it did not continue. it did not try again. it just stopped with that on the screen, above.

**Comment by habanoz** [comment]
Mirror selection mechanism added. It will select healthy mirrors. Tzscan calls are guarded to prevent application crashes. However, I will leave stack trace (at least for a while), it helps to locate failure points, as it did in this crash case.

**Comment by SemElVik** [comment]
Yesterday I stopped the TRD with an error of 502.
and the program just stopped. and I was not at home and could not connect remotely at that moment. it was not very convenient. I had to go home to restart the program. :)

Now it's great that there is a choice of mirrors.

**Comment by utdrmac** [comment]
@habanoz Can you reference the PR in this issue?

**Comment by habanoz** [comment]
@utdrmac Please check the commit referenced below:

https://github.com/habanoz/tezos-reward-distributor/commit/56de53e27c211fec63646caa9274676097baa4fc
