### ISSUE TITLE
Payouts fail for tz3 addresses

### ISSUE THREAD

**Issue by dordille** [habanoz/tezos-reward-distributor#79]
**Describe the bug**
Using a tz3 address with a remote signer result in transaction failures when transfer operation is injected into tezos node.

**To Reproduce**
Configure software to process payouts using a tz3 address as the source of funds, and run software.

**Expected behavior**
Rewards to be distributed properly.

**Comment by habanoz** [comment]
Thanks for PR #78 .

Merged. Closing. 

I will also merge it to V5 which will be shipped soon.
