### ISSUE TITLE
Producer_retry_fail, no failed payment files found

### ISSUE THREAD

**Issue by amani1104** [habanoz/tezos-reward-distributor#83]
**Describe the bug**
TRD failed to receive data from the tzscan API. As I ran it in dry-run mode, no entry was made in the payments/failed-folder. Now TRD tries to execute the failed payment every hour, but then issues the 'No failed payment files found under directory' error due to the missing entry. 

```
producer_retry_fail - retry_failed_payments started
producer_retry_fail - No failed payment files found under directory '/home/tezos/pymnt/reports/tz1XXX/payments/failed'
```

How can I get rid of the error? 

**Environment**
 - Source Code Build, v5
 - mainnet

**Comment by habanoz** [comment]
- TRD regularly checks failed directory. If it finds any failed report file, it is retired. If there is no failed payment report file, it is fine.
- Tzscan API failures does not create a failed payment report file, Tzscan API failures are always retried immediately.
- DRY run reporting directory is different than standard reporting directory.

Given the information above: BUG definition is not clear. The log part you shared does not indicate any error.

**Comment by amani1104** [comment]
If this is intended behaviour then it's fine. To me it appeared as an error message, given that a payment failed just before I noticed this behaviour.
