### ISSUE TITLE
RPC layer test on an Archive Node is Needed.

### ISSUE THREAD

**Issue by habanoz** [habanoz/tezos-reward-distributor#89]
RPC is fixed. However in order to use RPC layer for reward calculations you need to have an archive node. FULL node does not keep track of records to handle reward payments.

An rpc reward class is added to support use of public nodes to overcome this limitation. You can try it with -P prpc switch. Calculations on public RPC node works fine.

However, I am not able to test on a local rpc node. Because my node is a FULL node. May a community member with an ARCHIVE node can test with "-P rpc" ?

**Comment by jdsika** [comment]
@amzid will check this and improve the local node implemenation. For now I would propose to allow running the TRD only with an Archieve Node and check this property of the node before running any TRD operations.

**Comment by habanoz** [comment]
I agree. We need a way to understand type of the node.

**Comment by jdsika** [comment]
@amzid I am putting this here until it is done and I will merge the PR

KNOWN ISSUES:

    Payout with existing KT addresses not possible
    Logging issues (#113)

TO-DOs:

    Add sphinx documentation
    Make choice of public rpc node more flexible
    Remove tzscan completely from TRD and substitute it with tzstats

**Comment by jdsika** [comment]
Resolved with #127
