### ISSUE TITLE
Split Code and Configuration

### ISSUE THREAD

**Issue by habanoz** [habanoz/tezos-reward-distributor#9]
**Is your feature request related to a problem? Please describe.**
When BusinessConfiguration.py is updated, git pull causes problems.

**Describe the solution you'd like**
Use plain text configuration files e.g. ini,json,xml files to configure the application.

**Describe alternatives you've considered**
xml can be a good option because it can be validated. Json is more user-friendly. User recommendations are welcome.

**Comment by nurikabe** [comment]
I'd recommend YAML

**Comment by habanoz** [comment]
Thanks for the recommendation. I will consider. I would welcome any comparisons or additional recommendations.

**Comment by nurikabe** [comment]
Nothing scientific per se other than personal experience.

Many of the frameworks and systems I use today have adopted YAML for configuration. Random examples off the top of my head include Docker Compose, GitLab config, Travis config, NestJS config, Symfony config, and so on.

YAML is nice becasue it's both machine validatable and human-friendly. XML configs are always a PITA to read through. JSON's not bad but I think the strict Python-like indentation rules of YAML ensure that it's always easy to grok.

**Comment by habanoz** [comment]
YAML is the new configuration choice.
