### ISSUE TITLE
service_add.py Error

### ISSUE THREAD

**Issue by dmirgaleev** [habanoz/tezos-reward-distributor#92]
While using "sudo python3.6 service_add.py" an error occurred:
Traceback (most recent call last):
  File "service_add.py", line 35, in <module>
    main()
  File "service_add.py", line 17, in main
    content = content.replace("<USER>", os.getlogin())
FileNotFoundError: [Errno 2] No such file or directory
Enviroment:
Ubuntu 16.04
Python 3.6.8

**Comment by habanoz** [comment]
Try to use full path. 

e.g. /home/someuser/tezos-reward-distributor/service_add.py

**Comment by dmirgaleev** [comment]
Thanks for your reply! I have the same error.
Command: `sudo python3.6 /home/a/tezos-reward-distributor/service_add.py`
Response:
```
Traceback (most recent call last):
  File "/home/a/tezos-reward-distributor/service_add.py", line 35, in <module>
    main()
  File "/home/a/tezos-reward-distributor/service_add.py", line 17, in main
    content = content.replace("<USER>", os.getlogin())
FileNotFoundError: [Errno 2] No such file or directory
```

**Comment by habanoz** [comment]
Could you please do a "git pull" and try again?

**Comment by dmirgaleev** [comment]
Unfortunately, the same problem
![image](https://user-images.githubusercontent.com/35151170/60026460-49e41c80-96a4-11e9-90ba-4bdc6b66d620.png)

**Comment by habanoz** [comment]
Something is not right about your installation. You haven’t pulled recent changes. Can you make a fresh clone and try again?

**Comment by dmirgaleev** [comment]
Thanks a lot! That's working
