### ISSUE TITLE
Build pipeline: TravisCi or CircleCi for better project quality

### ISSUE THREAD

**Issue by jdsika** [habanoz/tezos-reward-distributor#97]
**Is your feature request related to a problem? Please describe.**
As a part of the contribution process the master branch should be protected and PRs are only merge-able if the build pipeline executes successful. In addition at best two maintainers should be named who are able to merge into the master branch or if desired into a developer branch.

**Describe the solution you'd like**
Integrate CircleCI or TravisCI into the project configuration

**Additional context**
In addition to the build itself different rule sets for code integrity and style guides can be executed in order to maintain quality.

**Comment by habanoz** [comment]
Thanks for the suggestion. Travis-CI integration is setup. I created a branch named development. PR's will be sent to development branch and development branch will be merged to master if all tests passes. 

PR's will not be pulled without proper unit tests. Another developer can be given the right to accept pull requests into development branch. Master branch should be left as is, at least for the time being.

@jdsika are you interested in being the second maintainer?

**Comment by jdsika** [comment]
Yes sure, I would offer a hand here :)

**Comment by habanoz** [comment]
Closing. Please feel free to re-open.
